export const ui = {
  sv: {
    brandName: 'Lös verkliga problem',
    brandSub: 'Sverige-först problem intelligence',
    navTop10: 'Top 10 Problems',
    navAllProblems: 'All Problems',
    navMission: 'Mission',
    heroEyebrow: 'Sverige-first founder intelligence',
    missionLabel: 'Vårt uppdrag',
    missionTitle: 'Lös verkliga problem',
    missionBody: 'Vi vill göra det lättare att börja på rätt plats: där svenska människor, hushåll, företag och institutioner faktiskt känner friktion. Inte med en lista över allt — utan med ett koncentrerat urval av det som verkligen förtjänar att byggas kring.',
    footerLeft: 'Lös verkliga problem — Top 10 per kategori, byggt för verklig efterfrågan.',
    footerRight: 'Sverige-först problem intelligence',
    rank: 'Rank',
    problemScore: 'Problemscore',
    market: 'Marknad',
    trust: 'Tillit'
  },
  en: {
    brandName: 'Solve real-world problems',
    brandSub: 'Sweden-first problem intelligence',
    navTop10: 'Top 10 Problems',
    navAllProblems: 'All Problems',
    navMission: 'Mission',
    heroEyebrow: 'Sweden-first founder intelligence',
    missionLabel: 'Our mission',
    missionTitle: 'Solve real-world problems',
    missionBody: 'We want to make it easier to start in the right place: where people, households, companies and institutions in Sweden actually feel friction. Not with a list of everything — but with a concentrated selection of what truly deserves to be built around.',
    footerLeft: 'Solve real-world problems — Top 10 per category, built for real demand.',
    footerRight: 'Sweden-first problem intelligence',
    rank: 'Rank',
    problemScore: 'Problem score',
    market: 'Market',
    trust: 'Trust'
  }
} as const;


export const categories = {
  'public-sector-welfare': {
    sv: { name: 'Offentlig sektor & välfärd', subtitle: 'Medborgare möter återkommande friktion kring tillgång, handläggningstider, digitalt utanförskap och samordning mellan svenska välfärdsmyndigheter.' },
    en: { name: 'Public Sector & Welfare', subtitle: 'Citizens face recurring friction in access, processing times, digital exclusion, and coordination across Swedish welfare agencies.' },
    items: [
      { sv: ['Långa handläggningstider för ersättningar', 'Många upplever ekonomisk stress när beslut om sjukpenning, föräldrapenning, bostadsbidrag eller aktivitetsersättning dröjer.', ['Försäkringskassan', 'Reddit'], [92, 87, 85]], en: ['Long benefit processing times', 'People report financial stress while waiting for sickness benefit, parental benefit, housing allowance, or activity compensation decisions.', ['Försäkringskassan', 'Reddit'], [92, 87, 85]] },
      { sv: ['Svårbegripliga välfärdsregler', 'Medborgare har svårt att förstå behörighet, intygskrav och hur inkomstförändringar påverkar ersättningar.', ['Försäkringskassan', 'Hallå Konsument'], [90, 85, 88]], en: ['Hard-to-understand welfare rules', 'Citizens struggle to know eligibility, documentation needs, and how income changes affect benefits.', ['Försäkringskassan', 'Hallå Konsument'], [90, 85, 88]] },
      { sv: ['Splittrad kontakt med myndigheter', 'Invånare måste upprepa samma information till flera myndigheter eftersom system och ärendeansvar samordnas bristfälligt.', ['DIGG', 'SKR'], [88, 84, 88]], en: ['Fragmented contact with authorities', 'People must repeat the same information to multiple agencies because systems and case ownership are poorly coordinated.', ['DIGG', 'SKR'], [88, 84, 88]] },
      { sv: ['Digitalt utanförskap i offentlig service', 'BankID, e-tjänster och appbaserade flöden stänger ute vissa äldre, personer med funktionsnedsättning, nyanlända och personer utan stabil digital tillgång.', ['PTS', 'Internetstiftelsen'], [86, 83, 87]], en: ['Digital exclusion from public services', 'BankID, e-services, and app-only flows exclude some elderly people, disabled users, newcomers, and people without stable digital access.', ['PTS', 'Internetstiftelsen'], [86, 83, 87]] },
      { sv: ['Svårt att nå handläggare', 'Medborgare klagar på telefonköer, begränsade öppettider, otydligt ansvar och brist på direkta ärendeuppdateringar.', ['Försäkringskassan', 'Flashback'], [84, 83, 84]], en: ['Difficulty reaching public case officers', 'Citizens complain about phone queues, limited opening hours, unclear responsibility, and lack of direct case updates.', ['Försäkringskassan', 'Flashback'], [84, 83, 84]] },
      { sv: ['Stora skillnader i kommunal service', 'Tillgång till socialtjänst, skolstöd, äldreomsorg och LSS-stöd skiljer sig kraftigt mellan kommuner.', ['SKR', 'Socialstyrelsen'], [82, 81, 87]], en: ['Municipal service quality varies widely', 'Access to social services, school support, elder care, and disability support differs significantly by municipality.', ['SKR', 'Socialstyrelsen'], [82, 81, 87]] },
      { sv: ['Överklaganden är långsamma och svåra', 'Personer som får avslag på välfärdsbeslut upplever ofta överklaganden som juridiskt svåra, långsamma och psykiskt påfrestande.', ['Domstol', 'Försäkringskassan'], [80, 80, 86]], en: ['Appeals are slow and intimidating', 'People who receive rejected welfare decisions often find appeals legally complex, slow, and emotionally draining.', ['Domstol', 'Försäkringskassan'], [80, 80, 86]] },
      { sv: ['Offentlig upphandling missar användarbehov', 'Medborgare och personal möter stelbenta system och tjänster som köpts in utifrån pris eller kravlista snarare än faktisk användbarhet.', ['Upphandlingsmyndigheten', 'Konkurrensverket'], [78, 79, 86]], en: ['Public procurement misses user needs', 'Citizens and staff experience rigid systems and services bought on price or compliance rather than actual usability.', ['Upphandlingsmyndigheten', 'Konkurrensverket'], [78, 79, 86]] },
      { sv: ['Kontroll mot bidragsfusk skapar felaktig misstänkliggörning', 'Legitima ersättningstagare kan känna sig misstänkliggjorda eller belastade av upprepade kontroller, intyg och återkrav.', ['Försäkringskassan', 'Riksrevisionen'], [76, 78, 86]], en: ['Welfare fraud controls create false suspicion', 'Legitimate claimants can feel distrusted or burdened by repeated checks, documents, and retroactive repayment demands.', ['Försäkringskassan', 'Riksrevisionen'], [76, 78, 86]] },
      { sv: ['Otillgängligt myndighetsspråk', 'Myndighetsinformation skrivs ofta på byråkratisk svenska som är svår för personer med låg läsvana, funktionsnedsättning eller begränsad svenska.', ['isof.se', 'myndigheterna.se'], [74, 77, 75]], en: ['Inaccessible public information language', 'Public instructions are often written in bureaucratic Swedish that is difficult for people with low literacy, disabilities, or limited Swedish.', ['isof.se', 'myndigheterna.se'], [74, 77, 75]] },
    ]
  },
  'housing-real-estate': {
    sv: { name: 'Bostad & fastighet', subtitle: 'Sveriges bostadsmarknad skapar friktion genom brist, otydliga köer, renoveringstvister, energikostnader och svaga konsumentupplevelser.' },
    en: { name: 'Housing & Real Estate', subtitle: 'Sweden’s housing market creates friction through shortages, opaque queues, renovation disputes, energy costs, and weak consumer protection experiences.' },
    items: [
      { sv: ['Långa köer till hyresrätter', 'I storstäder kan människor vänta många år på förstahandskontrakt och tvingas till osäkra andrahandslösningar.', ['bostadsformedlingen.se', 'Boverket'], [92, 86, 83]], en: ['Long rental housing queues', 'People in major cities can wait many years for first-hand rental contracts, pushing them into insecure sublets.', ['bostadsformedlingen.se', 'Boverket'], [92, 86, 83]] },
      { sv: ['Otrygg och dyr andrahandsuthyrning', 'Hyresgäster möter olagliga hyror, korta kontrakt, plötsliga uppsägningar och svårigheter att bevisa överhyror.', ['hyresgastforeningen.se', 'Reddit'], [90, 86, 80]], en: ['Unsafe and overpriced subletting', 'Tenants face illegal rents, short contracts, sudden terminations, and difficulty proving overcharges.', ['hyresgastforeningen.se', 'Reddit'], [90, 86, 80]] },
      { sv: ['Dolda fel efter bostadsköp', 'Köpare upptäcker fuktskador, undermåliga renoveringar eller elfel efter köp och har svårt att utkräva ansvar.', ['ARN', 'konsumentverket.se'], [88, 85, 83]], en: ['Hidden defects after home purchases', 'Buyers discover moisture damage, poor renovations, or electrical faults after purchase and struggle to assign responsibility.', ['ARN', 'konsumentverket.se'], [88, 85, 83]] },
      { sv: ['Misstro mot budgivningar', 'Köpare oroar sig för falska bud, stressande säljtaktik, bristande insyn och svårigheter att kontrollera budhistorik.', ['fmi.se', 'Flashback'], [86, 84, 79]], en: ['Bidding process distrust', 'Buyers worry about fake bids, pressure tactics, poor transparency, and limited ability to verify bidding history.', ['fmi.se', 'Flashback'], [86, 84, 79]] },
      { sv: ['Avgiftshöjningar i bostadsrättsföreningar', 'Stigande räntor och underhållsskulder tvingar BRF:er att höja avgifter, vilket överraskar hushåll med svag insyn i föreningens ekonomi.', ['SCB', 'Boverket'], [84, 82, 87]], en: ['Housing association fee shocks', 'Rising interest rates and maintenance debt force BRFs to raise monthly fees, surprising households with weak insight into association finances.', ['SCB', 'Boverket'], [84, 82, 87]] },
      { sv: ['Tvister med hantverkare', 'Bostadsägare klagar på förseningar, dåligt utfört arbete, otydliga offerter och svårigheter att få fel åtgärdade.', ['ARN', 'Hallå Konsument'], [82, 82, 82]], en: ['Renovation contractor disputes', 'Homeowners complain about delays, poor workmanship, unclear quotes, and difficulty getting defects corrected.', ['ARN', 'Hallå Konsument'], [82, 82, 82]] },
      { sv: ['Osäkra energikostnader i bostäder', 'Hushåll har svårt att förutse värme- och elkostnader, särskilt i äldre hus och fastigheter med svaga energideklarationer.', ['Energimyndigheten', 'Boverket'], [80, 80, 86]], en: ['Energy cost uncertainty in homes', 'Households struggle to predict heating and electricity costs, especially in older houses and poorly energy-declared properties.', ['Energimyndigheten', 'Boverket'], [80, 80, 86]] },
      { sv: ['Konflikter om mögel och inomhusmiljö', 'Hyresgäster och ägare möter hälsorisker och ansvarstvister kring ventilation, fukt och mögelsanering.', ['Folkhälsomyndigheten', 'Boverket'], [78, 79, 86]], en: ['Mold and indoor environment conflicts', 'Tenants and owners face health concerns and responsibility disputes over ventilation, dampness, and mold remediation.', ['Folkhälsomyndigheten', 'Boverket'], [78, 79, 86]] },
      { sv: ['Förseningar och kvalitetsproblem i nyproduktion', 'Köpare av nyproducerade bostäder drabbas av inflyttningsförseningar, ändrade specifikationer, fel och osäkerhet vid tvister med byggbolag.', ['ARN', 'konsumentverket.se'], [76, 79, 81]], en: ['New-build delays and quality problems', 'Buyers of new apartments face delayed occupancy, changed specifications, defects, and uncertainty during developer disputes.', ['ARN', 'konsumentverket.se'], [76, 79, 81]] },
      { sv: ['Svårt att jämföra verklig boendekostnad', 'Köpare måste väga ihop ränta, avgift, energi, amortering, föreningsskuld, skatt och underhåll utan en tydlig standardbild.', ['finansinspektionen.se', 'konsumentverket.se'], [74, 77, 80]], en: ['Difficulty comparing real housing affordability', 'Buyers must combine mortgage rates, fees, energy, amortization, BRF debt, tax, and maintenance without a clear standard view.', ['finansinspektionen.se', 'konsumentverket.se'], [74, 77, 80]] },
    ]
  },
  'healthtech': {
    sv: { name: 'Hälsoteknik', subtitle: 'Svenska patienter möter problem med tillgång, data, triagering, användbarhet och tillit när vården blir mer digital och kapacitetsbegränsad.' },
    en: { name: 'Healthtech', subtitle: 'Swedish patients face access, data, triage, usability, and trust problems as healthcare becomes more digital and capacity-constrained.' },
    items: [
      { sv: ['Långa väntetider till vårdcentral', 'Patienter har svårt att få tider i tid och bollas mellan telefonköer, digitala formulär och triagesjuksköterskor.', ['1177.se', 'Socialstyrelsen'], [92, 86, 83]], en: ['Long waits for primary care appointments', 'Patients struggle to get timely appointments and often bounce between phone queues, digital forms, and triage nurses.', ['1177.se', 'Socialstyrelsen'], [92, 86, 83]] },
      { sv: ['Ojämlik tillgång till specialistvård', 'Väntetider och remisshantering varierar mellan regioner, vilket får patienter att söka privata alternativ eller nya bedömningar.', ['vantetider.se', 'Socialstyrelsen'], [90, 85, 83]], en: ['Uneven access to specialist care', 'Waiting times and referral handling vary by region, causing patients to seek private alternatives or second opinions.', ['vantetider.se', 'Socialstyrelsen'], [90, 85, 83]] },
      { sv: ['Digital triagering missar patientens sammanhang', 'Symtomformulär och chattflöden kan upplevas stela, så användare måste upprepa information eller oroar sig för att viktiga detaljer missas.', ['1177.se', 'Reddit'], [88, 85, 80]], en: ['Digital triage misses patient context', 'Symptom checkers and chat flows can feel rigid, leading users to repeat information or worry that important details are ignored.', ['1177.se', 'Reddit'], [88, 85, 80]] },
      { sv: ['Splittrade journaler mellan vårdgivare', 'Patienter förväntar sig att vårdgivare ser relevant historik, men åtkomst skiljer sig mellan regioner, privata kliniker och kommunal vård.', ['ehalsomyndigheten.se', 'imy.se'], [86, 83, 77]], en: ['Fragmented medical records between providers', 'Patients expect providers to see relevant history, but data access differs between regions, private clinics, and municipal care.', ['ehalsomyndigheten.se', 'imy.se'], [86, 83, 77]] },
      { sv: ['Förvirring kring läkemedelslistor', 'Patienter och anhöriga hittar inaktuella recept, dubbla läkemedel och otydliga dosinstruktioner i olika system.', ['ehalsomyndigheten.se', 'lakemedelsverket.se'], [84, 82, 77]], en: ['Medication list confusion', 'Patients and caregivers find outdated prescriptions, duplicate medicines, and unclear dosage instructions across systems.', ['ehalsomyndigheten.se', 'lakemedelsverket.se'], [84, 82, 77]] },
      { sv: ['Bristande tillgång till psykisk vård', 'Personer med ångest, depression, ADHD eller utmattning rapporterar långa väntetider, oklara vägar in och ojämn uppföljning.', ['Socialstyrelsen', 'Folkhälsomyndigheten'], [82, 81, 87]], en: ['Mental healthcare access gaps', 'People with anxiety, depression, ADHD, or burnout report long waits, unclear pathways, and uneven follow-up.', ['Socialstyrelsen', 'Folkhälsomyndigheten'], [82, 81, 87]] },
      { sv: ['Svåranvända vårdportaler', 'Patienter har problem med inloggning, gömda meddelanden, olika regionala gränssnitt och otydliga nästa steg efter digital kontakt.', ['1177.se', 'Internetstiftelsen'], [80, 80, 81]], en: ['Hard-to-use healthcare portals', 'Patients struggle with login, hidden messages, inconsistent regional interfaces, and unclear next steps after digital contact.', ['1177.se', 'Internetstiftelsen'], [80, 80, 81]] },
      { sv: ['Brist på återkoppling efter provtagning', 'Patienter ser provsvar utan tolkning eller väntar på att vården ska förklara om något behöver göras.', ['1177.se', 'Reddit'], [78, 80, 78]], en: ['Lack of feedback after tests', 'Patients see lab values without interpretation or wait for clinicians to explain whether action is needed.', ['1177.se', 'Reddit'], [78, 80, 78]] },
      { sv: ['Integritetsoro i digital vård', 'Användare oroar sig för vem som kan se känsliga hälsodata, särskilt i appar, privata digitala vårdgivare och sammanhållna journaler.', ['imy.se', 'ehalsomyndigheten.se'], [76, 78, 76]], en: ['Privacy concerns in digital health', 'Users worry about who can access sensitive health data, especially in apps, private digital providers, and shared records.', ['imy.se', 'ehalsomyndigheten.se'], [76, 78, 76]] },
      { sv: ['Egenvårdsbörda vid kronisk sjukdom', 'Patienter med diabetes, astma, smärta eller hjärtsjukdom måste själva hålla koll på symtom, mätare, besök och livsstilsförändringar med begränsat stöd.', ['Socialstyrelsen', '1177.se'], [74, 77, 80]], en: ['Chronic disease self-management burden', 'Patients with diabetes, asthma, pain, or heart disease must track symptoms, devices, appointments, and lifestyle changes with limited support.', ['Socialstyrelsen', '1177.se'], [74, 77, 80]] },
    ]
  },
  'elder-care': {
    sv: { name: 'Äldreomsorg', subtitle: 'Svensk äldreomsorg pressas av bemanning, samordning, ensamhet, säkerhet, anhörigbörda och ojämn kommunal kvalitet.' },
    en: { name: 'Elder Care', subtitle: 'Elder care in Sweden is strained by staffing, coordination, loneliness, safety, family burden, and uneven municipal quality.' },
    items: [
      { sv: ['Hög personalomsättning i hemtjänsten', 'Äldre behöver upprepa rutiner och behov för ny personal, vilket minskar trygghet och kontinuitet.', ['Socialstyrelsen', 'kommunal.se'], [92, 86, 83]], en: ['Home care staff turnover', 'Older people must repeatedly explain routines and needs to new staff, reducing trust and continuity.', ['Socialstyrelsen', 'kommunal.se'], [92, 86, 83]] },
      { sv: ['Korta och stressade hemtjänstbesök', 'Hemtjänstpersonal har ofta pressade scheman, vilket gör att äldre känner sig osedda och praktiska uppgifter inte hinns med.', ['ivo.se', 'Socialstyrelsen'], [90, 85, 83]], en: ['Short and rushed home care visits', 'Care workers often have tight schedules, leaving older people feeling unseen and practical tasks unfinished.', ['ivo.se', 'Socialstyrelsen'], [90, 85, 83]] },
      { sv: ['Ensamhet bland äldre', 'Många äldre saknar regelbunden social kontakt trots praktiskt stöd, vilket ökar psykiska och fysiska hälsorisker.', ['Folkhälsomyndigheten', 'Socialstyrelsen'], [88, 84, 88]], en: ['Loneliness among older adults', 'Many elderly people lack regular social contact despite receiving practical support, increasing mental and physical health risks.', ['Folkhälsomyndigheten', 'Socialstyrelsen'], [88, 84, 88]] },
      { sv: ['Läkemedelsmisstag i äldreomsorgen', 'Komplexa läkemedelsrutiner, delegering och bristande informationsöverföring ökar risken för missade eller felaktiga doser.', ['ivo.se', 'Socialstyrelsen'], [86, 83, 82]], en: ['Medication mistakes in elder care', 'Complex medication routines, delegation, and poor information transfer increase risks of missed or wrong doses.', ['ivo.se', 'Socialstyrelsen'], [86, 83, 82]] },
      { sv: ['Anhöriga saknar stöd', 'Anhöriga samordnar ofta vård, tider, ekonomi och akuta situationer utan tillräcklig vägledning eller avlastning.', ['anhoriga.se', 'Socialstyrelsen'], [84, 82, 82]], en: ['Family caregivers lack support', 'Relatives often coordinate care, appointments, finances, and emergencies without enough guidance or respite.', ['anhoriga.se', 'Socialstyrelsen'], [84, 82, 82]] },
      { sv: ['Svår övergång från sjukhus till hemmet', 'Äldre som skrivs ut från sjukhus kan få glapp i rehab, bostadsanpassning, läkemedelsändringar och kommunalt stöd.', ['ivo.se', 'SKR'], [82, 81, 82]], en: ['Difficult transition from hospital to home', 'Older patients discharged from hospital may face gaps in rehab, home adaptations, medication updates, and municipal support.', ['ivo.se', 'SKR'], [82, 81, 82]] },
      { sv: ['Fallrisker i hemmet', 'Äldre löper stor fallrisk på grund av hinder, dålig belysning, läkemedelseffekter och försenade bostadsanpassningar.', ['MSB', 'Socialstyrelsen'], [80, 80, 86]], en: ['Fall risks at home', 'Older people remain at high risk of falls due to obstacles, poor lighting, medication effects, and delayed home adaptations.', ['MSB', 'Socialstyrelsen'], [80, 80, 86]] },
      { sv: ['Svårt att välja äldreomsorgsutförare', 'Familjer har svårt att jämföra kvalitet, bemanning, kontinuitet, språkkompetens och klagomålshistorik mellan utförare.', ['Socialstyrelsen', 'ivo.se'], [78, 79, 81]], en: ['Hard to choose elder care provider', 'Families struggle to compare quality, staffing, continuity, language skills, and complaint history across providers.', ['Socialstyrelsen', 'ivo.se'], [78, 79, 81]] },
      { sv: ['Bristande samordning vid demens', 'Personer med demens och anhöriga möter splittrad diagnosprocess, dagverksamhet, hemtjänst, säkerhetsåtgärder och framtidsplanering.', ['demenscentrum.se', 'Socialstyrelsen'], [76, 78, 81]], en: ['Dementia care coordination gaps', 'People with dementia and relatives face fragmented diagnosis, day activities, home care, safety measures, and future planning.', ['demenscentrum.se', 'Socialstyrelsen'], [76, 78, 81]] },
      { sv: ['Välfärdsteknik skapar oro', 'Digitala lås, nattkameror, larm och sensorer kan öka trygghet men också skapa förvirring, integritetsoro eller användningsfel.', ['imy.se', 'Socialstyrelsen'], [74, 77, 80]], en: ['Welfare technology creates anxiety', 'Digital locks, night cameras, alarms, and sensors can improve safety but also cause confusion, privacy worries, or failed use.', ['imy.se', 'Socialstyrelsen'], [74, 77, 80]] },
    ]
  },
  'greentech-sustainability': {
    sv: { name: 'Grön teknik & hållbarhet', subtitle: 'Svenska hushåll och företag möter praktisk hållbarhetsfriktion kring energi, transport, återvinning, renovering och trovärdiga klimatval.' },
    en: { name: 'GreenTech & Sustainability', subtitle: 'Swedish households and businesses face practical sustainability friction around energy, transport, recycling, renovation, and credible climate choices.' },
    items: [
      { sv: ['Svängiga elpriser', 'Hushåll har svårt att förstå timpris, nätavgifter, avtal och när elanvändning faktiskt är billigast.', ['energimarknadsbyran.se', 'Energimyndigheten'], [92, 86, 83]], en: ['Electricity price volatility', 'Households struggle to understand hourly pricing, grid fees, contracts, and when energy use is actually cheapest.', ['energimarknadsbyran.se', 'Energimyndigheten'], [92, 86, 83]] },
      { sv: ['Tvister kring solceller', 'Konsumenter rapporterar aggressiv försäljning, otydliga återbetalningskalkyler, installationsförseningar, växelriktarproblem och garantiförvirring.', ['ARN', 'konsumentverket.se'], [90, 86, 83]], en: ['Solar panel sales and installation disputes', 'Consumers report aggressive sales, unclear payback claims, delayed installations, inverter issues, and warranty confusion.', ['ARN', 'konsumentverket.se'], [90, 86, 83]] },
      { sv: ['Laddningsbrist i flerbostadshus', 'Boende i flerbostadshus och BRF:er möter kostnads-, ansvars-, nätkapacitets- och parkeringskonflikter kring laddning.', ['Energimyndigheten', 'Boverket'], [88, 84, 88]], en: ['EV charging access in apartment housing', 'Apartment residents and BRFs face cost, responsibility, grid capacity, and parking allocation conflicts for charging.', ['Energimyndigheten', 'Boverket'], [88, 84, 88]] },
      { sv: ['Förvirrande återvinningsregler', 'Många är osäkra på hur förpackningar, textil, elektronik, matavfall och farligt avfall ska sorteras i olika kommuner.', ['avfallsverige.se', 'sopor.nu'], [86, 83, 77]], en: ['Confusing recycling rules', 'People are unsure how to sort packaging, textiles, electronics, food waste, and hazardous waste across municipalities.', ['avfallsverige.se', 'sopor.nu'], [86, 83, 77]] },
      { sv: ['Greenwashing i konsumentprodukter', 'Konsumenter har svårt att kontrollera hållbarhetspåståenden, klimatmärkningar, återvunnet innehåll och “eko”-marknadsföring.', ['konsumentverket.se', 'Hallå Konsument'], [84, 82, 87]], en: ['Greenwashing in consumer products', 'Shoppers find it difficult to verify sustainability claims, climate labels, recycled content, and “eco” marketing.', ['konsumentverket.se', 'Hallå Konsument'], [84, 82, 87]] },
      { sv: ['Svårt att välja värmepump', 'Villaägare har svårt att jämföra luftvärme, bergvärme, fjärrvärmealternativ, installationskvalitet, stöd och livscykelkostnader.', ['Energimyndigheten', 'ARN'], [82, 82, 82]], en: ['Heat pump selection complexity', 'Homeowners struggle to compare air-source, ground-source, district heating alternatives, installation quality, subsidies, and lifetime costs.', ['Energimyndigheten', 'ARN'], [82, 82, 82]] },
      { sv: ['Matsvinn i hushåll', 'Konsumenter vill minska svinn men har svårt med planering, datummärkning, portionsstorlek, förvaring och rester.', ['Livsmedelsverket', 'naturvardsverket.se'], [80, 80, 81]], en: ['Food waste at household level', 'Consumers want to reduce waste but struggle with planning, date labels, portion sizes, storage, and leftovers.', ['Livsmedelsverket', 'naturvardsverket.se'], [80, 80, 81]] },
      { sv: ['Reparation och återbruk är krångligt', 'Att reparera elektronik, kläder, möbler och vitvaror är ofta långsammare, dyrare eller mindre tillgängligt än att köpa nytt.', ['konsumentverket.se', 'naturskyddsforeningen.se'], [78, 79, 81]], en: ['Circular repair is inconvenient', 'Repairing electronics, clothes, furniture, and appliances is often slower, more expensive, or less accessible than buying new.', ['konsumentverket.se', 'naturskyddsforeningen.se'], [78, 79, 81]] },
      { sv: ['Småföretag har svårt med hållbarhetsrapportering', 'Småföretag möter kund- och regeltryck att mäta utsläpp och leverantörspåverkan utan tydliga verktyg eller kompetens.', ['Tillväxtverket', 'Vinnova'], [76, 78, 86]], en: ['Small businesses struggle with sustainability reporting', 'SMEs face customer and regulatory pressure to measure emissions and supply-chain impact without clear tools or expertise.', ['Tillväxtverket', 'Vinnova'], [76, 78, 86]] },
      { sv: ['Klimatanpassning blir dyr för fastighetsägare', 'Översvämning, värme, skyfall och dräneringsrisker skapar otydligt ansvar och dyra förebyggande åtgärder för hus och fastigheter.', ['MSB', 'smhi.se'], [74, 77, 80]], en: ['Climate adaptation costs for property owners', 'Flooding, heat, heavy rain, and drainage risks create unclear responsibility and expensive preventive work for homes and properties.', ['MSB', 'smhi.se'], [74, 77, 80]] },
    ]
  },
  'integration-immigration': {
    sv: { name: 'Integration & migration', subtitle: 'Nyanlända i Sverige möter hinder kring språk, arbete, bostad, byråkrati, kompetensvalidering och social tillhörighet.' },
    en: { name: 'Integration & Immigration', subtitle: 'Newcomers in Sweden face barriers in language, work, housing, bureaucracy, recognition of skills, and social belonging.' },
    items: [
      { sv: ['Lång väg till fungerande svenska', 'Nyanlända behöver ofta svenska för jobb och samhällsservice men möter ojämn SFI-kvalitet, väntetider och få träningsmöjligheter.', ['Skolverket', 'Arbetsförmedlingen'], [92, 86, 88]], en: ['Slow path to Swedish language proficiency', 'Newcomers often need Swedish for work and services but face uneven SFI quality, waiting times, and limited practice opportunities.', ['Skolverket', 'Arbetsförmedlingen'], [92, 86, 88]] },
      { sv: ['Svårt att använda utländska meriter', 'Invandrare med utbildning eller yrkeserfarenhet har svårt med validering, legitimation, översättning och arbetsgivares förtroende.', ['uhr.se', 'Socialstyrelsen'], [90, 85, 83]], en: ['Foreign credentials are hard to use', 'Immigrants with education or professional experience struggle with validation, licensing, translation, and employer trust.', ['uhr.se', 'Socialstyrelsen'], [90, 85, 83]] },
      { sv: ['Svårt att få första jobbet utan svenska referenser', 'Arbetssökande hamnar i ett moment 22 där svensk erfarenhet, nätverk och referenser krävs innan de kan få dem.', ['Arbetsförmedlingen', 'SCB'], [88, 84, 88]], en: ['First job barrier without Swedish references', 'Jobseekers face a catch-22 where Swedish experience, networks, and references are required before they can obtain them.', ['Arbetsförmedlingen', 'SCB'], [88, 84, 88]] },
      { sv: ['Bostadsdiskriminering och svag tillgång till hyresmarknaden', 'Nyanlända har problem med köer, inkomstkrav, avsaknad av referenser, trångboddhet och möjlig diskriminering.', ['do.se', 'Boverket'], [86, 83, 82]], en: ['Housing discrimination and weak rental access', 'Newcomers struggle with queues, income requirements, lack of references, overcrowding, and possible discrimination.', ['do.se', 'Boverket'], [86, 83, 82]] },
      { sv: ['Byråkrati före personnummer', 'Utan personnummer eller BankID kan nyanlända hindras från bank, bostad, vårdbokning, jobb och mobilabonnemang.', ['skatteverket.se', 'migrationsverket.se'], [84, 82, 77]], en: ['Bureaucracy before personal identity number', 'Without a personnummer or BankID, newcomers can be blocked from banking, housing, healthcare booking, jobs, and mobile subscriptions.', ['skatteverket.se', 'migrationsverket.se'], [84, 82, 77]] },
      { sv: ['Osäkerhet kring anhöriginvandring', 'Familjer möter långa väntetider, dokumentkrav, försörjningskrav och psykisk stress under anhörigprocesser.', ['migrationsverket.se', 'roks.se'], [82, 81, 77]], en: ['Family reunification uncertainty', 'Families face long waits, documentation demands, income requirements, and emotional stress during reunification processes.', ['migrationsverket.se', 'roks.se'], [82, 81, 77]] },
      { sv: ['Svårt att förstå svenska arbetsplatsnormer', 'Nyanställda kan missförstå informella regler kring kommunikation, hierarki, fika, fack, sjukfrånvaro och förväntningar.', ['Arbetsförmedlingen', 'unionen.se'], [80, 80, 81]], en: ['Difficulty understanding Swedish workplace norms', 'New employees may misunderstand informal rules around communication, hierarchy, fika, unions, sick leave, and expectations.', ['Arbetsförmedlingen', 'unionen.se'], [80, 80, 81]] },
      { sv: ['Social isolering efter ankomst', 'Nyanlända saknar ofta svenska vänner, lokala nätverk och vardagliga sammanhang utanför formella integrationsprogram.', ['Folkhälsomyndigheten', 'SCB'], [78, 79, 86]], en: ['Social isolation after arrival', 'Newcomers often lack Swedish friends, local networks, and everyday arenas for belonging beyond formal integration programs.', ['Folkhälsomyndigheten', 'SCB'], [78, 79, 86]] },
      { sv: ['Utrikes födda kvinnor står längre från arbetsmarknaden', 'Utrikes födda kvinnor möter samlade hinder från barnomsorg, språk, nätverk, diskriminering, utbildningsgap och hälsa.', ['Arbetsförmedlingen', 'jamstalldhetsmyndigheten.se'], [76, 78, 81]], en: ['Immigrant women face labor-market exclusion', 'Foreign-born women face combined barriers from childcare, language, networks, discrimination, education gaps, and health.', ['Arbetsförmedlingen', 'jamstalldhetsmyndigheten.se'], [76, 78, 81]] },
      { sv: ['Samhällsinformation är svår att hitta på flera språk', 'Viktiga regler om skola, vård, skatt, arbete och välfärd är utspridda och finns inte alltid i tydliga översatta format.', ['informationsverige.se', 'migrationsverket.se'], [74, 77, 75]], en: ['Public information is hard to navigate in multiple languages', 'Important rules on school, healthcare, tax, work, and welfare are scattered and not always available in clear translated formats.', ['informationsverige.se', 'migrationsverket.se'], [74, 77, 75]] },
    ]
  },
  'consumer-services': {
    sv: { name: 'Vardagstjänster', subtitle: 'Svenska konsumenter rapporterar vardagsfriktion kring abonnemang, leveranser, reparationer, bank, resor, kundtjänst och klagomål.' },
    en: { name: 'Consumer Services', subtitle: 'Swedish consumers report everyday friction in subscriptions, deliveries, repairs, banking, travel, customer support, and complaint handling.' },
    items: [
      { sv: ['Krångligt att säga upp abonnemang', 'Konsumenter klagar på dolda uppsägningstider, uppsägning endast via telefon, otydliga villkor och fortsatt debitering.', ['konsumentverket.se', 'Trustpilot'], [92, 87, 83]], en: ['Subscription cancellation friction', 'Consumers complain about hidden notice periods, phone-only cancellation, unclear terms, and continued billing.', ['konsumentverket.se', 'Trustpilot'], [92, 87, 83]] },
      { sv: ['Problem med paketleveranser', 'Kunder drabbas av missade leveranser, otydliga ombud, skadade paket och tvister mellan butik och transportör.', ['ARN', 'Trustpilot'], [90, 87, 78]], en: ['Parcel delivery failures', 'Customers face missed deliveries, unclear pickup points, damaged parcels, and disputes between retailer and carrier.', ['ARN', 'Trustpilot'], [90, 87, 78]] },
      { sv: ['Kundtjänst är långsam eller svårnådd', 'Konsumenter möter chattbotar, långa köer, inget telefonnummer, upprepade överlämningar och olösta ärenden.', ['Reco', 'Trustpilot'], [88, 86, 78]], en: ['Customer support is slow or inaccessible', 'Consumers encounter chatbots, long queues, no phone number, repeated handoffs, and unresolved cases.', ['Reco', 'Trustpilot'], [88, 86, 78]] },
      { sv: ['Prisjämförelser döljer totalkostnad', 'Konsumenter har svårt att jämföra avgifter, tillägg, frakt, bindningstid, försäkring och dynamiska priser.', ['konsumentverket.se', 'Hallå Konsument'], [86, 83, 87]], en: ['Price comparison hides total cost', 'Consumers struggle to compare fees, add-ons, delivery, binding periods, insurance, and dynamic pricing.', ['konsumentverket.se', 'Hallå Konsument'], [86, 83, 87]] },
      { sv: ['Tvister vid begagnat bilköp', 'Köpare rapporterar dolda fel, garantibråk, vilseledande annonser och svårigheter att bevisa vad som utlovats.', ['ARN', 'Hallå Konsument'], [84, 83, 82]], en: ['Used car purchase disputes', 'Buyers report hidden faults, warranty disagreements, misleading ads, and difficulty proving what was promised.', ['ARN', 'Hallå Konsument'], [84, 83, 82]] },
      { sv: ['Kvalitetsproblem med städ- och flyttjänster', 'Kunder klagar på missade tider, skador, dålig städning, otydliga RUT-avdrag och svag reklamationshantering.', ['ARN', 'Reco'], [82, 83, 77]], en: ['Home cleaning and moving service quality gaps', 'Customers complain about missed times, damage, poor cleaning, unclear RUT deductions, and weak complaint handling.', ['ARN', 'Reco'], [82, 83, 77]] },
      { sv: ['Tvister om resor, återbetalning och förseningar', 'Resenärer möter nekad återbetalning, press att ta värdebevis, oklara rättigheter och långsam ersättning vid inställda eller försenade resor.', ['ARN', 'konsumentverket.se'], [80, 81, 81]], en: ['Travel refund and delay disputes', 'Travelers face denied refunds, voucher pressure, unclear rights, and slow compensation for cancelled or delayed trips.', ['ARN', 'konsumentverket.se'], [80, 81, 81]] },
      { sv: ['Bank- och betalkonton spärras eller krånglar', 'Konsumenter kan stoppas av BankID-problem, penningtvättskontroller, bedrägeriflaggor eller bristande digital support.', ['finansinspektionen.se', 'konsumenternas.se'], [78, 79, 76]], en: ['Banking and payment account lockouts', 'Consumers can be blocked by BankID issues, anti-money-laundering checks, fraud flags, or poor digital support.', ['finansinspektionen.se', 'konsumenternas.se'], [78, 79, 76]] },
      { sv: ['Klagomål på telekomtäckning och avtal', 'Kunder rapporterar dålig mobiltäckning, bredbandsavbrott, routerproblem, prishöjningar och svåravslutade avtal.', ['PTS', 'ARN'], [76, 79, 81]], en: ['Telecom coverage and contract complaints', 'Customers report poor mobile coverage, broadband outages, router issues, price hikes, and hard-to-exit contracts.', ['PTS', 'ARN'], [76, 79, 81]] },
      { sv: ['Svårt att använda reklamationsrätten', 'Konsumenter vet ofta inte om de ska kontakta säljare, tillverkare, marknadsplats, ARN, försäkringsbolag eller betalningsleverantör.', ['Hallå Konsument', 'ARN'], [74, 78, 80]], en: ['Complaint rights are hard to exercise', 'Consumers often do not know whether to contact seller, manufacturer, marketplace, ARN, insurer, or payment provider.', ['Hallå Konsument', 'ARN'], [74, 78, 80]] },
    ]
  },
  'home-services': {
    sv: { name: 'Hem & bostad', subtitle: 'Svenska hushåll möter återkommande problem med bostadsreparationer, renoveringskvalitet, energiåtgärder och tillit till lokala tjänsteleverantörer.' },
    en: { name: 'Home Services', subtitle: 'Swedish households face recurring friction around housing repairs, renovation quality, energy upgrades, and trust in local service providers.' },
    items: [
      { sv: ['Otydliga slutkostnader vid renovering', 'Villa- och bostadsägare upplever att offerter blir betydligt dyrare fakturor på grund av otydliga uppskattningar, tillägg och bristande dokumentation.', ['konsumentverket.se', 'ARN'], [92, 87, 83]], en: ['Unclear final renovation costs', 'Homeowners report quotes turning into much higher invoices due to vague estimates, add-ons, and poor documentation.', ['konsumentverket.se', 'ARN'], [92, 87, 83]] },
      { sv: ['Svårt att bedöma hantverkares kvalitet', 'Konsumenter har svårt att skilja seriösa hantverkare från opålitliga firmor innan arbetet börjar, särskilt vid mindre uppdrag.', ['Reco', 'Trustpilot'], [90, 87, 78]], en: ['Hard to verify tradesperson quality', 'Consumers struggle to distinguish serious contractors from unreliable firms before work starts, especially for small jobs.', ['Reco', 'Trustpilot'], [90, 87, 78]] },
      { sv: ['Tvister om felaktiga badrumsrenoveringar', 'Våtrumsfel leder till dyra tvister om ansvar, försäkringsskydd och om arbetet följt svenska branschregler.', ['ARN', 'konsumentverket.se'], [88, 85, 83]], en: ['Disputes over faulty bathroom renovations', 'Wet-room defects create expensive disputes about responsibility, insurance coverage, and whether work followed Swedish industry rules.', ['ARN', 'konsumentverket.se'], [88, 85, 83]] },
      { sv: ['Långa väntetider för småreparationer i hemmet', 'Hushåll har ofta svårt att få elektriker, rörmokare eller snickare att snabbt ta mindre uppdrag.', ['Flashback', 'Reddit'], [86, 85, 81]], en: ['Long waiting times for small home repairs', 'Households often cannot get electricians, plumbers, or carpenters to take smaller jobs quickly.', ['Flashback', 'Reddit'], [86, 85, 81]] },
      { sv: ['Krånglig administration kring ROT-avdrag', 'Kunder och hantverkare möter osäkerhet kring villkor, fakturaupplägg och avdrag som nekas.', ['skatteverket.se', 'konsumentverket.se'], [84, 82, 82]], en: ['Confusing ROT deduction administration', 'Customers and contractors face uncertainty around eligibility, invoice structure, and rejected deductions.', ['skatteverket.se', 'konsumentverket.se'], [84, 82, 82]] },
      { sv: ['Bristande kommunikation från fastighetsförvaltare', 'Hyresgäster och bostadsrättsföreningar klagar på långsam återkoppling, otydlig status och olösta felanmälningar.', ['hyresgastforeningen.se', 'Flashback'], [82, 82, 79]], en: ['Poor communication from property managers', 'Tenants and housing associations complain about slow responses, unclear status updates, and unresolved maintenance cases.', ['hyresgastforeningen.se', 'Flashback'], [82, 82, 79]] },
      { sv: ['Svårt att jämföra energirenoveringar', 'Villaägare har svårt att bedöma värmepumpar, isolering, solceller och återbetalningstid när priser och stöd ändras.', ['Energimyndigheten', 'Boverket'], [80, 80, 86]], en: ['Energy renovation decisions are hard to compare', 'Homeowners struggle to assess heat pumps, insulation, solar panels, and payback times amid changing prices and subsidies.', ['Energimyndigheten', 'Boverket'], [80, 80, 86]] },
      { sv: ['Vilseledande hemförsäljning av bostadstjänster', 'Konsumenter rapporterar påstridig försäljning och otydliga avtal för larm, energitjänster, städning eller serviceabonnemang.', ['konsumentverket.se', 'Hallå Konsument'], [78, 79, 86]], en: ['Misleading door-to-door home service sales', 'Consumers report pressure selling and unclear contracts for alarms, energy services, cleaning, or maintenance subscriptions.', ['konsumentverket.se', 'Hallå Konsument'], [78, 79, 86]] },
      { sv: ['Städservice håller ojämn kvalitet', 'Kunder klagar på missade moment, personalbyten, skador och svårigheter att få ersättning efter dålig städning.', ['Trustpilot', 'Reco'], [76, 80, 76]], en: ['Cleaning service quality varies widely', 'Customers complain about missed tasks, changing staff, damage, and difficulty getting compensation after poor cleaning.', ['Trustpilot', 'Reco'], [76, 80, 76]] },
      { sv: ['Bostadsanpassning upplevs som långsam', 'Äldre och personer med funktionsnedsättning möter långa kommunala processer för ramper, badrumsändringar och tillgänglighetsåtgärder.', ['Boverket', 'Socialstyrelsen'], [74, 77, 85]], en: ['Housing adaptation processes feel slow', 'Elderly or disabled residents face lengthy municipal processes for ramps, bathroom changes, and accessibility fixes.', ['Boverket', 'Socialstyrelsen'], [74, 77, 85]] },
    ]
  },
  'fintech-payments': {
    sv: { name: 'Fintech & betalningar', subtitle: 'Svenska konsumenter och småföretag möter betalningsutanförskap, bedrägeririsker, skuldproblem och tillitsbrister när pengatjänster blir mer digitala.' },
    en: { name: 'FinTech & Payments', subtitle: 'Swedish consumers and small businesses experience payment exclusion, fraud risk, debt friction, and trust issues as money services become more digital.' },
    items: [
      { sv: ['BankID-beroende stänger ute vissa användare', 'Personer utan BankID, smartphone, svenskt personnummer eller digital vana får svårt att använda viktiga tjänster.', ['PTS', 'DIGG'], [92, 86, 88]], en: ['BankID dependence excludes some users', 'People without BankID, smartphones, Swedish personal identity numbers, or stable digital skills struggle to access essential services.', ['PTS', 'DIGG'], [92, 86, 88]] },
      { sv: ['Äldre är sårbara för betalningsbedrägerier', 'Bedragare utnyttjar tillit, BankID-signering, Swishöverföringar och falska banksamtal riktade mot äldre.', ['Polisen', 'brottsförebygganderådet.se'], [90, 85, 78]], en: ['Elderly people are vulnerable to payment fraud', 'Fraudsters exploit trust, BankID signing, Swish transfers, and fake bank calls targeting older consumers.', ['Polisen', 'brottsförebygganderådet.se'], [90, 85, 78]] },
      { sv: ['Felaktiga Swishbetalningar är svåra att få tillbaka', 'Användare som skickar pengar till fel nummer är ofta beroende av mottagarens vilja att betala tillbaka.', ['Hallå Konsument', 'Reddit'], [88, 85, 85]], en: ['Swish mistakes are hard to reverse', 'Users who send money to the wrong number often depend on the recipient’s willingness to return it.', ['Hallå Konsument', 'Reddit'], [88, 85, 85]] },
      { sv: ['Småhandlare pressas av kort- och betalkostnader', 'Kaféer, butiker och tjänsteföretag möter splittrade terminaler, inlösenavgifter, försenade utbetalningar och bindningstider.', ['foretagarna.se', 'svensktnaringsliv.se'], [86, 83, 77]], en: ['Small merchants struggle with card and payment fees', 'Cafés, shops, and service firms face fragmented terminals, acquiring fees, payout delays, and contract lock-ins.', ['foretagarna.se', 'svensktnaringsliv.se'], [86, 83, 77]] },
      { sv: ['Köp-nu-betala-senare skapar skuldförvirring', 'Konsumenter rapporterar missade fakturor, oväntade avgifter och svårigheter att hålla koll på flera uppskjutna betalningar.', ['konsumentverket.se', 'kronofogden.se'], [84, 82, 82]], en: ['Buy-now-pay-later creates debt confusion', 'Consumers report missed invoices, unexpected fees, and difficulty tracking multiple deferred payments.', ['konsumentverket.se', 'kronofogden.se'], [84, 82, 82]] },
      { sv: ['Svårt för nyanlända att öppna bankkonto', 'Nyanlända och migranter kan möta förseningar på grund av ID, adress, inkomst eller regelefterlevnadskrav.', ['finansinspektionen.se', 'migrationsverket.se'], [82, 81, 77]], en: ['Bank account access is difficult for newcomers', 'New residents and migrants can face delays due to ID, address, income, or compliance requirements.', ['finansinspektionen.se', 'migrationsverket.se'], [82, 81, 77]] },
      { sv: ['Bolånekunder upplever ränteförhandling som otydlig', 'Låntagare har svårt att förstå rabatter, jämförelseräntor, bankmarginaler och när de bör omförhandla.', ['finansinspektionen.se', 'konsumenternas.se'], [80, 80, 76]], en: ['Mortgage customers find rate negotiation opaque', 'Borrowers struggle to understand discounts, comparison rates, bank margins, and when to renegotiate.', ['finansinspektionen.se', 'konsumenternas.se'], [80, 80, 76]] },
      { sv: ['Abonnemangsbetalningar är svåra att avsluta', 'Konsumenter klagar på återkommande dragningar som fortsätter efter uppsägning eller provperioder.', ['konsumentverket.se', 'ARN'], [78, 80, 81]], en: ['Subscription payments are hard to cancel', 'Consumers complain about recurring charges continuing after cancellations or free trials.', ['konsumentverket.se', 'ARN'], [78, 80, 81]] },
      { sv: ['Kreditupplysningar påverkar vardagsköp', 'Konsumenter frustreras när faktura, leasing, telekom eller e-handel leder till kreditupplysningar eller avslag.', ['konsumenternas.se', 'Flashback'], [76, 79, 78]], en: ['Credit checks affect everyday purchases', 'Consumers are frustrated when invoicing, leasing, telecom, or e-commerce purchases trigger credit checks or rejections.', ['konsumenternas.se', 'Flashback'], [76, 79, 78]] },
      { sv: ['Kontantfria tjänster minskar tillgängligheten', 'Personer som är beroende av kontanter möter hinder i butiker, transport, vårdnära tjänster och landsbygd.', ['riksbank.se', 'lansstyrelsen.se'], [74, 77, 75]], en: ['Cashless services reduce accessibility', 'People dependent on cash face barriers in shops, transport, healthcare-adjacent services, and rural areas.', ['riksbank.se', 'lansstyrelsen.se'], [74, 77, 75]] },
    ]
  },
  'logistics-delivery-infrastructure': {
    sv: { name: 'Logistik, leverans & infrastruktur', subtitle: 'Svenska konsumenter och företag möter problem med leveranssäkerhet, landsbygdstäckning, pakethantering och infrastrukturella flaskhalsar.' },
    en: { name: 'Logistics, Delivery & Infrastructure', subtitle: 'Sweden’s consumers and businesses face delivery reliability, rural coverage, parcel handling, and infrastructure bottlenecks.' },
    items: [
      { sv: ['Paket hamnar på opraktiska utlämningsställen', 'Kunder får ofta paket långt hemifrån trots närmare boxar eller ombud, särskilt under hög belastning.', ['postnord.se', 'Reddit'], [92, 87, 80]], en: ['Parcel deliveries go to inconvenient pickup points', 'Customers often receive parcels far from home despite nearby lockers or stores, especially during peak periods.', ['postnord.se', 'Reddit'], [92, 87, 80]] },
      { sv: ['Hemleveransers tidsfönster håller inte', 'Konsumenter klagar på missade tidsfönster, “ej hemma”-aviseringar och bristande realtidsinformation.', ['Trustpilot', 'ARN'], [90, 87, 78]], en: ['Home delivery time windows are unreliable', 'Consumers complain about missed delivery windows, “not home” notices, and little real-time communication.', ['Trustpilot', 'ARN'], [90, 87, 78]] },
      { sv: ['Landsbygdsleveranser är långsammare och mer osäkra', 'Hushåll och företag utanför städer har färre leveransval, längre ledtider och högre kostnader.', ['PTS', 'Tillväxtverket'], [88, 84, 88]], en: ['Rural delivery is slower and less predictable', 'Households and firms outside cities face fewer delivery options, longer lead times, and higher costs.', ['PTS', 'Tillväxtverket'], [88, 84, 88]] },
      { sv: ['Returer är krångliga för e-handelskunder', 'Kunder har problem med etiketter, emballage, återbetalningsdröjsmål och oklart ansvar när returpaket försvinner.', ['konsumentverket.se', 'ARN'], [86, 84, 82]], en: ['Returns are cumbersome for e-commerce shoppers', 'Shoppers struggle with labels, packaging, refund delays, and unclear responsibility when return parcels disappear.', ['konsumentverket.se', 'ARN'], [86, 84, 82]] },
      { sv: ['Transportskador är svåra att reklamera', 'Konsumenter och småsäljare möter ansvarsförskjutning mellan transportör, butik och försäkringsbolag vid skadat gods.', ['Hallå Konsument', 'ARN'], [84, 83, 82]], en: ['Delivery damage disputes are hard to resolve', 'Consumers and small sellers face blame-shifting between carrier, store, and insurer after damaged goods.', ['Hallå Konsument', 'ARN'], [84, 83, 82]] },
      { sv: ['Kylkedjan vid matleverans brister ibland', 'Matkasse- och livsmedelskunder rapporterar tinade varor, saknade produkter och osäker livsmedelssäkerhet efter förseningar.', ['Livsmedelsverket', 'Trustpilot'], [82, 82, 82]], en: ['Cold-chain delivery quality is inconsistent', 'Grocery and meal-kit customers report thawed goods, missing items, and uncertain food safety after delays.', ['Livsmedelsverket', 'Trustpilot'], [82, 82, 82]] },
      { sv: ['Bygglogistik skapar störningar i städer', 'Leveranser till byggarbetsplatser skapar köer, buller, blockerade gator och konflikter med boende och företag.', ['Trafikverket', 'stockholm.se'], [80, 80, 81]], en: ['Construction logistics cause urban disruption', 'Deliveries to construction sites create congestion, noise, blocked streets, and conflicts with residents and businesses.', ['Trafikverket', 'stockholm.se'], [80, 80, 81]] },
      { sv: ['Laddinfrastruktur begränsar elektriska godstransporter', 'Åkerier möter osäkerhet kring depåladdning, publik snabbladdning för lastbilar, nätkapacitet och ruttplanering.', ['Trafikverket', 'Energimyndigheten'], [78, 79, 86]], en: ['Charging infrastructure limits electric freight', 'Hauliers face uncertainty around depot charging, public fast charging for trucks, grid capacity, and route planning.', ['Trafikverket', 'Energimyndigheten'], [78, 79, 86]] },
      { sv: ['Arbetsvillkor i sista milen är pressade', 'Bud och förare rapporterar tidspress, oklar anställningsform, trafikrisker och varierande inkomster.', ['arbetsmiljoverket.se', 'transportarbetaren.se'], [76, 78, 76]], en: ['Last-mile delivery work conditions are strained', 'Couriers and drivers report time pressure, unclear employment status, traffic risk, and variable earnings.', ['arbetsmiljoverket.se', 'transportarbetaren.se'], [76, 78, 76]] },
      { sv: ['Trafikstörningar saknar användbar information', 'Pendlare och godsaktörer har svårt med sena, splittrade eller vaga uppdateringar vid infrastruktursstörningar.', ['Trafikverket', 'sj.se'], [74, 77, 80]], en: ['Rail and road disruptions lack actionable updates', 'Commuters and freight operators struggle with late, fragmented, or vague updates during infrastructure disruptions.', ['Trafikverket', 'sj.se'], [74, 77, 80]] },
    ]
  },
  'mobility-micromobility': {
    sv: { name: 'Mobilitet & mikromobilitet', subtitle: 'Svenska mobilitetsanvändare möter opålitliga reskedjor, parkeringskonflikter, laddluckor och säkerhetsproblem i både städer och glesbygd.' },
    en: { name: 'Mobility & Micromobility', subtitle: 'Swedish mobility users face unreliable multimodal travel, parking conflicts, charging gaps, and safety issues in dense and rural areas.' },
    items: [
      { sv: ['Kollektivtrafikstörningar är svåra att planera runt', 'Resenärer får ofullständig störningsinformation över buss, tåg, tunnelbana och regionala operatörer.', ['sl.se', 'Trafikverket'], [92, 86, 83]], en: ['Public transport disruptions are hard to plan around', 'Travellers get incomplete delay information across buses, trains, metros, and regional operators.', ['sl.se', 'Trafikverket'], [92, 86, 83]] },
      { sv: ['Sista kilometern saknas utanför stadskärnor', 'Boende i förorter och på landsbygd har svårt att ta sig från hemmet till stationer utan bil.', ['Trafikverket', 'Tillväxtverket'], [90, 85, 88]], en: ['First-and-last-mile gaps outside city centers', 'Suburban and rural residents struggle to connect from homes to stations without a car.', ['Trafikverket', 'Tillväxtverket'], [90, 85, 88]] },
      { sv: ['Elsparkcykelparkering blockerar gångbanor', 'Gående, rullstolsanvändare och synskadade möter sparkcyklar som lämnas på osäkra eller otillgängliga platser.', ['transportstyrelsen.se', 'synskadadesriksforbund.se'], [88, 84, 78]], en: ['E-scooter parking blocks pavements', 'Pedestrians, wheelchair users, and visually impaired people encounter scooters left in unsafe or inaccessible places.', ['transportstyrelsen.se', 'synskadadesriksforbund.se'], [88, 84, 78]] },
      { sv: ['Cykelinfrastruktur känns osäker på vintern', 'Is, bristande snöröjning, mörker och trafik konflikter minskar året-runt-cykling.', ['Trafikverket', 'cykelframjandet.se'], [86, 83, 82]], en: ['Cycling infrastructure feels unsafe in winter', 'Ice, snow clearance gaps, darkness, and road conflicts reduce year-round cycling.', ['Trafikverket', 'cykelframjandet.se'], [86, 83, 82]] },
      { sv: ['Köer och trasiga laddare frustrerar elbilsförare', 'Förare rapporterar upptagna, trasiga eller app-låsta laddare under resor och semesterperioder.', ['Energimyndigheten', 'Reddit'], [84, 83, 84]], en: ['EV charging queues and broken chargers frustrate drivers', 'Drivers report occupied, out-of-service, or app-locked chargers during trips and holidays.', ['Energimyndigheten', 'Reddit'], [84, 83, 84]] },
      { sv: ['Lägenhetsboende saknar hemmaladdning', 'Hyresgäster och bostadsrättsmedlemmar möter långsamma beslut, kostnadstvister och begränsad elektrifiering av parkeringar.', ['Boverket', 'Energimyndigheten'], [82, 81, 87]], en: ['Apartment residents lack home charging access', 'Tenants and housing association members face slow approvals, cost disputes, and limited parking electrification.', ['Boverket', 'Energimyndigheten'], [82, 81, 87]] },
      { sv: ['Bilpooler finns ojämnt tillgängliga', 'Användare utanför centrala stadsdelar hittar för få bilar, fel fordonstyper eller opraktiska upphämtningsplatser.', ['stockholm.se', 'Reddit'], [80, 81, 78]], en: ['Car-sharing availability is uneven', 'Users outside central urban areas find too few cars, unsuitable vehicle types, or inconvenient pickup locations.', ['stockholm.se', 'Reddit'], [80, 81, 78]] },
      { sv: ['Mobilitetsappar kombinerar biljetter dåligt', 'Resenärer måste hantera separata appar, betalningar, zoner och regler för regionala resor.', ['samtrafiken.se', 'konsumentverket.se'], [78, 79, 81]], en: ['Mobility apps do not combine tickets well', 'Travellers must juggle separate apps, payment systems, zones, and rules for regional travel.', ['samtrafiken.se', 'konsumentverket.se'], [78, 79, 81]] },
      { sv: ['Bilberoende på landsbygden är dyrt', 'Hushåll utanför kollektivtrafiktäta områden har höga kostnader för bränsle, försäkring, reparationer och bilbyte.', ['SCB', 'Tillväxtverket'], [76, 78, 86]], en: ['Rural car dependence is costly', 'Households outside transit-rich areas face high fuel, insurance, repair, and replacement costs.', ['SCB', 'Tillväxtverket'], [76, 78, 86]] },
      { sv: ['Olycksrisker med mikromobilitet är otydliga', 'Förare och kommuner saknar tydlig bild av skador, hjälm, alkohol, vägutformning och tillsyn.', ['transportstyrelsen.se', 'Folkhälsomyndigheten'], [74, 77, 80]], en: ['Micromobility accident risk is poorly understood', 'Riders and municipalities lack clear understanding of injuries, helmets, alcohol, road design, and enforcement.', ['transportstyrelsen.se', 'Folkhälsomyndigheten'], [74, 77, 80]] },
    ]
  },
  'b2b-services': {
    sv: { name: 'B2B-tjänster', subtitle: 'Svenska företag, särskilt små och medelstora, möter återkommande problem inom regelefterlevnad, inköp, bemanning, marknadsföring och tjänstekvalitet.' },
    en: { name: 'B2B Services', subtitle: 'Swedish companies, especially SMEs, face persistent friction in compliance, procurement, staffing, marketing, and professional service quality.' },
    items: [
      { sv: ['Småföretag tyngs av regelbörda', 'Företagare lägger mycket tid på att förstå skatt, arbetsrätt, miljökrav och rapportering.', ['Tillväxtverket', 'foretagarna.se'], [92, 86, 83]], en: ['SMEs struggle with regulatory burden', 'Business owners spend significant time understanding tax, employment, environmental, and reporting requirements.', ['Tillväxtverket', 'foretagarna.se'], [92, 86, 83]] },
      { sv: ['Offentlig upphandling är svår för små leverantörer', 'Småföretag upplever upphandlingar som komplexa, tidskrävande och gynnande för större etablerade aktörer med administrativ kapacitet.', ['Upphandlingsmyndigheten', 'Konkurrensverket'], [90, 85, 88]], en: ['Public procurement is hard for small suppliers', 'SMEs find tenders complex, time-consuming, and biased toward larger incumbents with administrative capacity.', ['Upphandlingsmyndigheten', 'Konkurrensverket'], [90, 85, 88]] },
      { sv: ['Sena B2B-betalningar pressar likviditet', 'Leverantörer drabbas när större kunder försenar fakturor eller kräver långa betalningsvillkor.', ['foretagarna.se', 'kronofogden.se'], [88, 84, 78]], en: ['Late B2B payments strain cash flow', 'Suppliers suffer when larger customers delay invoices or impose long payment terms.', ['foretagarna.se', 'kronofogden.se'], [88, 84, 78]] },
      { sv: ['Svårt att hitta pålitliga redovisningskonsulter', 'Småföretag är beroende av extern redovisning men rapporterar ojämn rådgivningskvalitet, missade deadlines och svag kommunikation.', ['Reco', 'Trustpilot'], [86, 85, 77]], en: ['Finding reliable accountants is difficult', 'Small firms depend on external bookkeeping but report uneven advice quality, missed deadlines, and poor communication.', ['Reco', 'Trustpilot'], [86, 85, 77]] },
      { sv: ['Cybersäkerhet känns för dyrt för småföretag', 'Mindre företag vet att riskerna ökar men saknar budget, kompetens och praktisk vägledning.', ['MSB', 'Internetstiftelsen'], [84, 82, 87]], en: ['Cybersecurity feels unaffordable for SMEs', 'Smaller firms know risks are rising but lack budget, expertise, and practical guidance.', ['MSB', 'Internetstiftelsen'], [84, 82, 87]] },
      { sv: ['Rekrytering av specialistkompetens tar för lång tid', 'Arbetsgivare möter brist, höga lönekrav och långa rekryteringsprocesser inom tech, teknik, vård och yrkesarbeten.', ['Arbetsförmedlingen', 'svensktnaringsliv.se'], [82, 81, 82]], en: ['Recruiting specialized staff takes too long', 'Employers face shortages, high salary expectations, and long hiring processes in tech, engineering, healthcare, and skilled trades.', ['Arbetsförmedlingen', 'svensktnaringsliv.se'], [82, 81, 82]] },
      { sv: ['Konsultkvalitet är svår att bedöma före köp', 'Köpare har svårt att jämföra byråer, IT-konsulter, marknadsföringsfirmor och managementrådgivare bortom säljpåståenden.', ['LinkedIn', 'Reco'], [80, 82, 78]], en: ['Consultant quality is hard to assess before purchase', 'Buyers struggle to compare agencies, IT consultants, marketing firms, and management advisors beyond sales claims.', ['LinkedIn', 'Reco'], [80, 82, 78]] },
      { sv: ['Företagshälsa och rehabadministration är splittrad', 'Arbetsgivare måste samordna sjukfrånvaro, rehabilitering, företagshälsa och Försäkringskassans processer.', ['Försäkringskassan', 'arbetsmiljoverket.se'], [78, 79, 81]], en: ['Workplace health administration is fragmented', 'Employers must coordinate sick leave, rehabilitation, occupational health providers, and Försäkringskassan processes.', ['Försäkringskassan', 'arbetsmiljoverket.se'], [78, 79, 81]] },
      { sv: ['B2B-abonnemang är svåra att avsluta', 'Företag klagar på automatiska förlängningar, uppsägningstider, otydliga villkor och aggressiv säljuppföljning.', ['svensktnaringsliv.se', 'Trustpilot'], [76, 79, 76]], en: ['B2B subscriptions are hard to exit', 'Firms complain about automatic renewals, notice periods, unclear terms, and aggressive sales follow-up.', ['svensktnaringsliv.se', 'Trustpilot'], [76, 79, 76]] },
      { sv: ['Hållbarhetsrapportering pressar små leverantörer', 'Småföretag får datakrav från större kunder om utsläpp, arbetsvillkor och leverantörsled utan system för att svara.', ['Tillväxtverket', 'bolagsverket.se'], [74, 77, 80]], en: ['Sustainability reporting demands reach small suppliers', 'SMEs face data requests from larger customers on emissions, labor practices, and supply chains without systems to respond.', ['Tillväxtverket', 'bolagsverket.se'], [74, 77, 80]] },
    ]
  },
  'saas': {
    sv: { name: 'SaaS', subtitle: 'Svenska organisationer möter praktiska SaaS-problem kring integration, regelefterlevnad, fakturering, lokalisering, säkerhet och leverantörsberoende.' },
    en: { name: 'SaaS', subtitle: 'Swedish organizations experience practical SaaS problems around integration, compliance, billing, localization, security, and vendor dependence.' },
    items: [
      { sv: ['SaaS-verktyg passar dåligt med svenska arbetsflöden', 'Team får problem när globala verktyg saknar stöd för BankID, Swish, svenska bokföringsformat, löne regler eller lokala register.', ['fortnox.se', 'bolagsverket.se'], [92, 86, 78]], en: ['SaaS tools do not integrate with Swedish workflows', 'Teams struggle when global tools lack support for BankID, Swish, Swedish accounting formats, payroll rules, or local registers.', ['fortnox.se', 'bolagsverket.se'], [92, 86, 78]] },
      { sv: ['GDPR-ansvar är oklart för molntjänster', 'Köpare har svårt att bedöma personuppgiftsbiträden, underbiträden, överföringsregler och datalagring i SaaS-avtal.', ['imy.se', 'DIGG'], [90, 85, 83]], en: ['GDPR responsibility is unclear for cloud tools', 'Buyers struggle to assess processors, sub-processors, transfer rules, and data residency in SaaS contracts.', ['imy.se', 'DIGG'], [90, 85, 83]] },
      { sv: ['SaaS-sprawl ökar kostnaderna', 'Företag samlar på sig oanvända licenser, dubbla verktyg och oklart ägarskap mellan avdelningar.', ['LinkedIn', 'Breakit'], [88, 86, 80]], en: ['SaaS subscription sprawl increases costs', 'Companies accumulate unused licenses, duplicate tools, and unclear ownership across departments.', ['LinkedIn', 'Breakit'], [88, 86, 80]] },
      { sv: ['Leverantörsinlåsning gör byte svårt', 'Organisationer möter begränsad dataexport, specialintegrationer, omskolning och avtalsmässiga hinder.', ['Konkurrensverket', 'cio.com'], [86, 83, 82]], en: ['Vendor lock-in makes switching painful', 'Organizations face data export limitations, custom integrations, retraining, and contractual barriers.', ['Konkurrensverket', 'cio.com'], [86, 83, 82]] },
      { sv: ['Svagt svenskspråkigt stöd bromsar införande', 'Medarbetare tvekar inför verktyg med svag svensk dokumentation, support, mallar eller terminologi.', ['Trustpilot', 'LinkedIn'], [84, 84, 79]], en: ['Poor Swedish-language support slows adoption', 'Employees resist tools with weak Swedish documentation, support, templates, or terminology.', ['Trustpilot', 'LinkedIn'], [84, 84, 79]] },
      { sv: ['Kommunal SaaS-upphandling är långsam och riskfylld', 'Offentliga köpare måste balansera upphandlingsregler, säkerhetsgranskning, tillgänglighet, arkivering och budgetcykler.', ['Upphandlingsmyndigheten', 'DIGG'], [82, 81, 87]], en: ['Municipal SaaS procurement is slow and risky', 'Public-sector buyers must balance procurement rules, security reviews, accessibility, archiving, and budget cycles.', ['Upphandlingsmyndigheten', 'DIGG'], [82, 81, 87]] },
      { sv: ['Tillgänglighetskrav förbises', 'SaaS-produkter hos offentliga eller kundnära organisationer uppfyller inte alltid WCAG eller svenska tillgänglighetskrav.', ['DIGG', 'PTS'], [80, 80, 86]], en: ['Accessibility compliance is overlooked', 'SaaS products used by public or customer-facing organizations often fail WCAG or Swedish digital accessibility expectations.', ['DIGG', 'PTS'], [80, 80, 86]] },
      { sv: ['Säkerhetsgranskningar överväldigar små SaaS-köpare', 'Småföretag saknar kompetens för att bedöma autentisering, backup, incidenthantering, kryptering och leverantörsrisk.', ['MSB', 'Internetstiftelsen'], [78, 79, 86]], en: ['Security reviews overwhelm small SaaS buyers', 'SMEs lack expertise to evaluate authentication, backups, incident response, encryption, and supplier risk.', ['MSB', 'Internetstiftelsen'], [78, 79, 86]] },
      { sv: ['SaaS-fakturor är svåra att stämma av', 'Ekonomiteam hanterar utländsk moms, kortbetalningar, användarbaserade ändringar och kvitton utspridda hos anställda.', ['skatteverket.se', 'bokforingsnamnden.se'], [76, 78, 76]], en: ['SaaS invoices are hard to reconcile', 'Finance teams face foreign VAT, card payments, user-based changes, and receipts scattered across employees.', ['skatteverket.se', 'bokforingsnamnden.se'], [76, 78, 76]] },
      { sv: ['AI-SaaS skapar oro för datasekretess', 'Svenska företag och myndigheter oroar sig för att personal klistrar in känsliga kund-, patient- eller affärsdata i externa AI-verktyg.', ['imy.se', 'MSB'], [74, 77, 80]], en: ['AI SaaS creates data confidentiality concerns', 'Swedish firms and public bodies worry that staff paste sensitive customer, patient, or business data into external AI tools.', ['imy.se', 'MSB'], [74, 77, 80]] },
    ]
  },
  'edtech': {
    sv: { name: 'Lärande & kompetensutveckling', subtitle: 'Sveriges elever, skolor, arbetsgivare och utbildare möter brister i digital utbildningskvalitet, kompetensmatchning, tillgänglighet och livslångt lärande.' },
    en: { name: 'EdTech', subtitle: 'Sweden’s learners, schools, employers, and educators face gaps in digital learning quality, skills matching, accessibility, and lifelong upskilling.' },
    items: [
      { sv: ['Skolplattformar splittrar föräldrakommunikation', 'Föräldrar måste följa meddelanden, scheman, betyg, frånvaro och blanketter i krångliga kommunala och skolrelaterade system.', ['skolinspektionen.se', 'Reddit'], [92, 87, 80]], en: ['Digital school platforms fragment parent communication', 'Parents must track messages, schedules, grades, absence, and forms across confusing municipal and school systems.', ['skolinspektionen.se', 'Reddit'], [92, 87, 80]] },
      { sv: ['Lärare saknar tid att utvärdera EdTech', 'Lärare möter många appar men har begränsad tid att bedöma pedagogik, integritet, tillgänglighet och läroplanskoppling.', ['Skolverket', 'lararen.se'], [90, 85, 83]], en: ['Teachers lack time to evaluate EdTech tools', 'Educators face many apps but limited time to assess pedagogy, privacy, accessibility, and curriculum fit.', ['Skolverket', 'lararen.se'], [90, 85, 83]] },
      { sv: ['Vuxnas omställning är svår att navigera', 'Yrkesverksamma har svårt att jämföra Komvux, YH, högskolekurser, privata aktörer, behörighet, finansiering och jobbutfall.', ['Arbetsförmedlingen', 'myh.se'], [88, 84, 83]], en: ['Adult reskilling is hard to navigate', 'Workers struggle to compare Komvux, YH, university courses, private providers, eligibility, financing, and job outcomes.', ['Arbetsförmedlingen', 'myh.se'], [88, 84, 83]] },
      { sv: ['SFI saknar ofta arbetsnära relevans', 'Studerande och arbetsgivare upplever glapp mellan klassrumssvenska och språket som krävs i vård, bygg, service eller industri.', ['Skolverket', 'Arbetsförmedlingen'], [86, 83, 87]], en: ['Swedish language learning lacks work-context relevance', 'Learners and employers report gaps between classroom Swedish and language needed in healthcare, construction, service, or industry jobs.', ['Skolverket', 'Arbetsförmedlingen'], [86, 83, 87]] },
      { sv: ['Elever behöver mer stöd för matematikluckor', 'Skolor har svårt att identifiera och åtgärda ackumulerade matematikbrister inför övergångar till gymnasium eller högre studier.', ['Skolverket', 'skolinspektionen.se'], [84, 82, 82]], en: ['Students need more support for math gaps', 'Schools struggle to identify and address accumulated math weaknesses before upper-secondary or higher education transitions.', ['Skolverket', 'skolinspektionen.se'], [84, 82, 82]] },
      { sv: ['Digitalt lärande ökar distraktion', 'Elever, föräldrar och lärare rapporterar att skärmar och lärverktyg också skapar spel-, sociala medier- och koncentrationsproblem.', ['Folkhälsomyndigheten', 'Skolverket'], [82, 81, 87]], en: ['Digital learning increases distraction', 'Students, parents, and teachers report that screens and learning devices also create gaming, social media, and focus problems.', ['Folkhälsomyndigheten', 'Skolverket'], [82, 81, 87]] },
      { sv: ['Digitalt stöd för särskilda behov är ojämnt', 'Elever med dyslexi, neuropsykiatriska funktionsnedsättningar eller språkbehov får ojämn tillgång till hjälpmedel.', ['spsm.se', 'skolinspektionen.se'], [80, 80, 76]], en: ['Special-needs digital support is uneven', 'Students with dyslexia, neuropsychiatric disabilities, or language needs receive inconsistent access to assistive tools.', ['spsm.se', 'skolinspektionen.se'], [80, 80, 76]] },
      { sv: ['Arbetsgivare kan inte enkelt verifiera korta utbildningar', 'Mikromeriter, onlineintyg och bootcamp-påståenden är svåra att jämföra med faktisk arbetsförmåga.', ['Arbetsförmedlingen', 'LinkedIn'], [78, 80, 83]], en: ['Employers cannot verify short-course skills easily', 'Microcredentials, online certificates, and bootcamp claims are hard to compare with real workplace capability.', ['Arbetsförmedlingen', 'LinkedIn'], [78, 80, 83]] },
      { sv: ['Landsbygdselever har begränsat kursutbud', 'Elever utanför större städer kan sakna lokal tillgång till specialiserade lärare, avancerade kurser eller yrkesutbildningar.', ['Skolverket', 'SCB'], [76, 78, 86]], en: ['Rural learners have limited course access', 'Students outside larger cities may lack local access to specialized teachers, advanced courses, or vocational training options.', ['Skolverket', 'SCB'], [76, 78, 86]] },
      { sv: ['Integritetsoro bromsar EdTech', 'Skolor och kommuner oroar sig för elevdata, molnlagring, spårning, AI-verktyg och leverantörsavtal.', ['imy.se', 'Skolverket'], [74, 77, 80]], en: ['EdTech privacy concerns slow adoption', 'Schools and municipalities worry about student data, cloud storage, tracking, AI tools, and supplier contracts.', ['imy.se', 'Skolverket'], [74, 77, 80]] },
    ]
  },
  'food-beverage': {
    sv: { name: 'Mat & dryck', subtitle: 'Vardagliga mat- och dryckesproblem i Sverige handlar ofta om höga priser, kostbehov, leveranssäkerhet samt tillit till kvalitet och ursprung.' },
    en: { name: 'Food & Beverage', subtitle: 'Everyday food and drink problems in Sweden cluster around high prices, dietary needs, delivery reliability, and trust in quality and origin.' },
    items: [
      { sv: ['Matprispress för hushåll', 'Konsumenter har svårt att planera matinköp när basvaror är dyra och kampanjer är svåra att jämföra mellan kedjor.', ['SCB', 'konsumentverket.se'], [92, 86, 88]], en: ['Grocery price shock for households', 'Consumers struggle to plan meals as basic groceries remain expensive and promotions are hard to compare across chains.', ['SCB', 'konsumentverket.se'], [92, 86, 88]] },
      { sv: ['Krympflation och otydliga förpackningsförändringar', 'Kunder upplever sig vilseledda när förpackningar krymper eller jämförpriser ändras medan hyllpriset ser liknande ut.', ['konsumentverket.se', 'Reddit'], [90, 86, 85]], en: ['Shrinkflation and unclear pack-value changes', 'Shoppers feel misled when package sizes shrink or unit prices change while shelf prices look similar.', ['konsumentverket.se', 'Reddit'], [90, 86, 85]] },
      { sv: ['Begränsat utbud av prisvärd allergisäker mat', 'Personer med allergier eller celiaki möter högre priser, mindre utbud och oro för kontaminering i butik och på restaurang.', ['Livsmedelsverket', 'celiaki.se'], [88, 84, 83]], en: ['Limited affordable allergy-safe foods', 'People with allergies or celiac disease face higher prices, limited choices, and fear of contamination in stores and restaurants.', ['Livsmedelsverket', 'celiaki.se'], [88, 84, 83]] },
      { sv: ['Ojämn allergiinformation på restaurangmenyer', 'Gäster behöver ofta fråga personal eftersom allergenmärkning saknas, är vag eller inte känns tillförlitlig vid stressig servering.', ['Livsmedelsverket', 'konsumentverket.se'], [86, 83, 87]], en: ['Restaurant menu allergy information is inconsistent', 'Diners often must ask staff because allergen labels are missing, vague, or not trusted during busy service.', ['Livsmedelsverket', 'konsumentverket.se'], [86, 83, 87]] },
      { sv: ['Matleveranser kommer kalla, sena eller ofullständiga', 'Kunder klagar på sena leveranser, saknade varor, dålig återbetalning och oklart ansvar mellan plattform och restaurang.', ['Trustpilot', 'ARN'], [84, 84, 77]], en: ['Food delivery arrives cold, late, or incomplete', 'Customers complain about restaurant delivery delays, missing items, poor refund handling, and unclear responsibility between platform and restaurant.', ['Trustpilot', 'ARN'], [84, 84, 77]] },
      { sv: ['Svag tillgång till dagligvaror på landsbygden', 'Mindre orter och landsbygder kan ha långt till fullsorterade matbutiker, särskilt för personer utan bil.', ['Tillväxtverket', 'SCB'], [82, 81, 87]], en: ['Rural grocery access is weak', 'Smaller towns and rural areas can have long distances to full-service grocery stores, especially without a car.', ['Tillväxtverket', 'SCB'], [82, 81, 87]] },
      { sv: ['Förvirring kring bäst före och matsvinn', 'Hushåll slänger ätbar mat eftersom datum märkning, förvaringsråd och tecken på dålighet är svåra att tolka.', ['Livsmedelsverket', 'naturvardsverket.se'], [80, 80, 81]], en: ['Confusing best-before and food waste decisions', 'Households throw away edible food because date labels, storage advice, and spoilage signs are hard to interpret.', ['Livsmedelsverket', 'naturvardsverket.se'], [80, 80, 81]] },
      { sv: ['Svårt att verifiera svenskt ursprung och hållbarhetspåståenden', 'Konsumenter vill köpa lokalt och hållbart men har svårt att förstå märkningar, ursprungsregler och gröna påståenden.', ['konsumentverket.se', 'Livsmedelsverket'], [78, 79, 86]], en: ['Hard to verify Swedish origin and sustainability claims', 'Consumers want local and sustainable food but struggle to understand labels, origin rules, and green claims.', ['konsumentverket.se', 'Livsmedelsverket'], [78, 79, 86]] },
      { sv: ['Ojämnt utbud av alkoholfria sociala alternativ', 'Personer som minskar alkohol upplever att barer, event och restauranger fortfarande har få intressanta alkoholfria alternativ.', ['Folkhälsomyndigheten', 'Reddit'], [76, 79, 83]], en: ['Alcohol-free social options remain uneven', 'People reducing alcohol report that bars, events, and restaurants still offer limited interesting non-alcoholic choices.', ['Folkhälsomyndigheten', 'Reddit'], [76, 79, 83]] },
      { sv: ['Dyra luncher för arbetstagare och studenter', 'Restaurangluncher och campusmat har blivit dyra, vilket gör att många tar med enformig matlåda eller hoppar över lunch.', ['SCB', 'Flashback'], [74, 78, 82]], en: ['Lunch affordability for workers and students', 'Restaurant lunches and campus meals have become costly, pushing people toward repetitive packed meals or skipped lunches.', ['SCB', 'Flashback'], [74, 78, 82]] },
    ]
  },
  'ecommerce': {
    sv: { name: 'E-handel', subtitle: 'Svenska e-handelsproblem drivs av leveransosäkerhet, returer, betalningstvister, bedrägerier och krångel vid gränsöverskridande köp.' },
    en: { name: 'E-commerce', subtitle: 'Swedish e-commerce friction is driven by delivery uncertainty, returns, payment disputes, scams, and cross-border shopping complexity.' },
    items: [
      { sv: ['Paket hamnar på fel eller opraktiskt ombud', 'Kunder blir frustrerade när paket styrs långt bort, ändras sent eller är svåra att hämta utan bil.', ['Trustpilot', 'Reddit'], [92, 88, 80]], en: ['Parcel delivery to wrong or inconvenient pickup points', 'Customers are frustrated when parcels are routed far away, changed late, or impossible to collect without a car.', ['Trustpilot', 'Reddit'], [92, 88, 80]] },
      { sv: ['Returfraktkostnader och otydliga returvillkor', 'Kunder överraskas av returavgifter, korta tidsfrister och otydliga krav på varans skick efter onlineköp.', ['konsumentverket.se', 'Hallå Konsument'], [90, 85, 88]], en: ['Return shipping costs and unclear return rules', 'Shoppers are surprised by return fees, short deadlines, and confusing condition requirements after online purchases.', ['konsumentverket.se', 'Hallå Konsument'], [90, 85, 88]] },
      { sv: ['Återbetalningar dröjer efter returer', 'Konsumenter klagar på att butiker hanterar returer långsamt och håller pengar låsta i veckor.', ['ARN', 'Trustpilot'], [88, 86, 78]], en: ['Refunds take too long after returns', 'Consumers complain that stores confirm returns slowly and keep money locked for weeks.', ['ARN', 'Trustpilot'], [88, 86, 78]] },
      { sv: ['Falska webbutiker och bluffannonser', 'Svenska konsumenter möter kopierade butiker, vilseledande sociala medier-annonser och säljare som försvinner efter betalning.', ['konsumentverket.se', 'Polisen'], [86, 83, 82]], en: ['Fake webshops and scam ads', 'Swedish shoppers encounter cloned stores, misleading social media ads, and sellers that disappear after payment.', ['konsumentverket.se', 'Polisen'], [86, 83, 82]] },
      { sv: ['Oklart ansvar på marknadsplatser', 'Köpare har svårt att veta om plattform, säljare, betalbolag eller fraktbolag ansvarar när något går fel.', ['ARN', 'Hallå Konsument'], [84, 83, 82]], en: ['Marketplace accountability is unclear', 'Buyers struggle to know whether the platform, seller, payment provider, or carrier is responsible when something goes wrong.', ['ARN', 'Hallå Konsument'], [84, 83, 82]] },
      { sv: ['Tull, moms och avgifter överraskar vid utlandsköp', 'Köp från säljare utanför EU blir dyrare eller försenade eftersom extra avgifter inte framgår tydligt i kassan.', ['tullverket.se', 'postnord.se'], [82, 81, 77]], en: ['Customs, VAT, and fees surprise cross-border shoppers', 'Purchases from non-EU sellers become more expensive or delayed because extra charges are not clear at checkout.', ['tullverket.se', 'postnord.se'], [82, 81, 77]] },
      { sv: ['Köp nu betala senare skapar betalstress', 'Konsumenter riskerar missade fakturor, påminnelseavgifter och splittrade skulder över flera onlineköp.', ['konsumentverket.se', 'kronofogden.se'], [80, 80, 81]], en: ['Buy-now-pay-later creates payment stress', 'Consumers risk missed invoices, reminder fees, and fragmented debts across multiple online purchases.', ['konsumentverket.se', 'kronofogden.se'], [80, 80, 81]] },
      { sv: ['Produktrecensioner är svåra att lita på', 'Kunder misstänker manipulerade recensioner, betalda omdömen och filtrering av betyg hos butiker och marknadsplatser.', ['konsumentverket.se', 'Trustpilot'], [78, 80, 81]], en: ['Product reviews are hard to trust', 'Shoppers suspect manipulated reviews, incentivized ratings, and review filtering on stores and marketplaces.', ['konsumentverket.se', 'Trustpilot'], [78, 80, 81]] },
      { sv: ['Leverans och retur av skrymmande varor är krångligt', 'Möbler, vitvaror och stora paket innebär tidsbokning, missade leveranser, transportskador och dyra returer.', ['ARN', 'Trustpilot'], [76, 80, 76]], en: ['Bulky-item delivery and returns are painful', 'Furniture, appliances, and large packages involve booking windows, failed deliveries, damaged goods, and expensive returns.', ['ARN', 'Trustpilot'], [76, 80, 76]] },
      { sv: ['Hållbarhetspåståenden i e-handel känns vaga', 'Konsumenter kan inte enkelt jämföra klimatpåverkan, förpackningsavfall, transportval eller verkliga cirkulära påståenden.', ['konsumentverket.se', 'naturvardsverket.se'], [74, 77, 80]], en: ['Sustainability claims in e-commerce feel vague', 'Consumers cannot easily compare climate impact, packaging waste, transport choices, or real circularity claims.', ['konsumentverket.se', 'naturvardsverket.se'], [74, 77, 80]] },
    ]
  },
  'cold-climate-seasonal': {
    sv: { name: 'Kallt klimat & säsongsproblem', subtitle: 'Sveriges säsongsproblem kombinerar mörker, halka, snö, energikostnader, transportstörningar och underhåll av bostäder.' },
    en: { name: 'Cold Climate & Seasonal', subtitle: 'Sweden’s seasonal problems combine darkness, ice, snow, energy costs, transport disruption, and housing maintenance burdens.' },
    items: [
      { sv: ['Fallolyckor på isiga gator', 'Fotgängare, särskilt äldre, skadas när trottoarer, busshållplatser och övergångsställen är isiga eller dåligt sandade.', ['MSB', 'Socialstyrelsen'], [92, 86, 88]], en: ['Slips and falls on icy streets', 'Pedestrians, especially older people, are injured when sidewalks, bus stops, and crossings are icy or poorly gritted.', ['MSB', 'Socialstyrelsen'], [92, 86, 88]] },
      { sv: ['Vinterförseningar i pendlingen', 'Snö, is och kyla stör tåg, bussar, vägar och flyg och gör vardagspendlingen osäker.', ['Trafikverket', 'sj.se'], [90, 85, 83]], en: ['Winter commuting delays and cancellations', 'Snow, ice, and cold disrupt trains, buses, roads, and flights, making daily commuting unreliable.', ['Trafikverket', 'sj.se'], [90, 85, 83]] },
      { sv: ['Höga uppvärmningskostnader vid köldknäppar', 'Hushåll i villor och äldre lägenheter får kraftiga kostnadsökningar när el- och fjärrvärmebehovet stiger.', ['Energimyndigheten', 'SCB'], [88, 84, 88]], en: ['High heating bills during cold snaps', 'Households in villas and older apartments face sudden cost spikes when electricity and district heating demand rises.', ['Energimyndigheten', 'SCB'], [88, 84, 88]] },
      { sv: ['Torr och obekväm inomhusluft', 'Uppvärmda vinterbostäder kan orsaka torr hud, irriterade ögon, näsblod och sämre sömn.', ['Folkhälsomyndigheten', 'astmaoallergiforbundet.se'], [86, 83, 82]], en: ['Indoor air becomes dry and uncomfortable', 'Heated winter homes can cause dry skin, irritated eyes, nosebleeds, and poor sleep.', ['Folkhälsomyndigheten', 'astmaoallergiforbundet.se'], [86, 83, 82]] },
      { sv: ['Säsongsmörker påverkar humör och energi', 'Många upplever låg energi, störd sömn och depressiva symtom under de långa mörka månaderna.', ['1177.se', 'Folkhälsomyndigheten'], [84, 82, 82]], en: ['Seasonal darkness affects mood and energy', 'Many people report low energy, sleep disruption, and depressive symptoms during long dark months.', ['1177.se', 'Folkhälsomyndigheten'], [84, 82, 82]] },
      { sv: ['Oklart ansvar för snöröjning', 'Villaägare, hyresgäster, hyresvärdar, kommuner och företag kan vara osäkra på vem som ska skotta och sanda.', ['villaagarna.se', 'kommunal.se'], [82, 81, 77]], en: ['Snow clearing responsibility is confusing', 'Homeowners, tenants, landlords, municipalities, and businesses can be unsure who must clear snow and ice.', ['villaagarna.se', 'kommunal.se'], [82, 81, 77]] },
      { sv: ['Vinterförberedelser för bilen är dyra och stressiga', 'Bilägare behöver hantera däckbyte, batteriproblem, frusna lås, skrapning, parkeringsregler och försäkringsfrågor.', ['transportstyrelsen.se', 'konsumentverket.se'], [80, 80, 81]], en: ['Car winter readiness is costly and stressful', 'Drivers must handle tire changes, battery failures, frozen locks, scraping, parking rules, and insurance concerns.', ['transportstyrelsen.se', 'konsumentverket.se'], [80, 80, 81]] },
      { sv: ['Barnlogistik försvåras av snö och kyla', 'Föräldrar kämpar med lager på lager-kläder, blöta plagg, barnvagnar i snö, förseningar och skolans utevistelsekrav.', ['Försäkringskassan', 'Reddit'], [78, 80, 83]], en: ['Childcare logistics worsen in snow and cold', 'Parents struggle with layered clothing, wet gear, prams in snow, delayed transit, and school outdoor requirements.', ['Försäkringskassan', 'Reddit'], [78, 80, 83]] },
      { sv: ['Tak snö, isproppar och risk för vattenskador', 'Fastighetsägare möter farliga snölaster, istappar, blockerade hängrännor och läckage vid växlande tö och frost.', ['Boverket', 'lansforsakringar.se'], [76, 78, 81]], en: ['Roof snow, ice dams, and water damage risks', 'Property owners face dangerous snow loads, falling icicles, blocked gutters, and leakage from freeze-thaw cycles.', ['Boverket', 'lansforsakringar.se'], [76, 78, 81]] },
      { sv: ['Vårens pollensäsong är intensiv och svårplanerad', 'Allergiker kämpar med skiftande pollentoppar, läkemedelstiming, arbetsprestation och utomhusplaner.', ['Folkhälsomyndigheten', 'pollenrapporten.se'], [74, 77, 80]], en: ['Spring pollen season is intense and hard to plan for', 'Allergy sufferers struggle with shifting pollen peaks, medication timing, work performance, and outdoor plans.', ['Folkhälsomyndigheten', 'pollenrapporten.se'], [74, 77, 80]] },
    ]
  },
  'health-wellness-personal-care': {
    sv: { name: 'Hälsa, välmående & personlig vård', subtitle: 'Svenska problem inom hälsa och personlig vård rör väntetider, psykisk ohälsa, luckor i kvinnohälsa och svårnavigerade digitala och offentliga system.' },
    en: { name: 'Health, Wellness & Personal Care', subtitle: 'Swedish health and personal care pain points include access delays, mental health strain, women’s health gaps, and navigation of digital and public systems.' },
    items: [
      { sv: ['Långa väntetider till vårdcentral', 'Patienter har svårt att få tid i rimlig tid, särskilt för icke-akuta men ihållande besvär.', ['Socialstyrelsen', '1177.se'], [92, 86, 83]], en: ['Long waits for primary care appointments', 'Patients struggle to get timely appointments, especially for non-acute but persistent symptoms.', ['Socialstyrelsen', '1177.se'], [92, 86, 83]] },
      { sv: ['Svårt att få stöd för psykisk ohälsa', 'Personer som söker terapi eller utredning möter köer, remisshinder, höga privata kostnader och regionala skillnader.', ['Folkhälsomyndigheten', 'Socialstyrelsen'], [90, 85, 88]], en: ['Mental health support is hard to access', 'People seeking therapy or assessment face queues, referral barriers, high private costs, and uneven regional access.', ['Folkhälsomyndigheten', 'Socialstyrelsen'], [90, 85, 88]] },
      { sv: ['Utmattning och stressrelaterad sjukskrivning är vanligt', 'Arbetstagare upplever långvarig stress, svårt att få rehabilitering och osäkerhet kring sjukskrivningsregler.', ['Försäkringskassan', 'arbetsmiljoverket.se'], [88, 84, 83]], en: ['Burnout and stress-related sick leave remain common', 'Workers experience prolonged stress, difficulty getting rehabilitation, and uncertainty around sick-leave rules.', ['Försäkringskassan', 'arbetsmiljoverket.se'], [88, 84, 83]] },
      { sv: ['Tandvård är dyrt för vuxna', 'Vuxna skjuter upp tandläkarbesök eftersom kostnaderna är höga och stöden är svåra att förstå.', ['Försäkringskassan', 'konsumentverket.se'], [86, 83, 87]], en: ['Dental care is expensive for adults', 'Adults delay dental visits because costs are high and subsidies are hard to understand.', ['Försäkringskassan', 'konsumentverket.se'], [86, 83, 87]] },
      { sv: ['Kvinnors hälsobesvär avfärdas eller fördröjs', 'Patienter med endometrios, klimakteriebesvär, bäckensmärta eller hormonproblem beskriver långsam diagnos och ojämn vård.', ['Socialstyrelsen', '1177.se'], [84, 82, 82]], en: ['Women’s health complaints are dismissed or delayed', 'Patients with endometriosis, menopause symptoms, pelvic pain, or hormonal issues report slow diagnosis and inconsistent care.', ['Socialstyrelsen', '1177.se'], [84, 82, 82]] },
      { sv: ['Långa köer till ADHD- och autismutredning', 'Barn och vuxna kan vänta länge på neuropsykiatrisk utredning, vilket påverkar skola, arbete och stöd.', ['Socialstyrelsen', 'sverigesradio.se'], [82, 81, 82]], en: ['ADHD and autism assessment queues are long', 'Children and adults can wait a long time for neuropsychiatric assessment, affecting school, work, and support access.', ['Socialstyrelsen', 'sverigesradio.se'], [82, 81, 82]] },
      { sv: ['Digital vård skapar splittrade patientresor', 'Patienter använder appar, 1177, telefonköer och fysiska mottagningar men information och ansvar hänger inte alltid ihop.', ['1177.se', 'ivo.se'], [80, 80, 76]], en: ['Digital healthcare creates fragmented patient journeys', 'Patients use apps, 1177, phone queues, and physical clinics but information and responsibility do not always connect.', ['1177.se', 'ivo.se'], [80, 80, 76]] },
      { sv: ['Förvirring kring allergi och känslighet mot skönhetsprodukter', 'Konsumenter har svårt att identifiera irriterande ingredienser i hudvård, hårfärg, parfym och kosmetika.', ['lakemedelsverket.se', 'astmaoallergiforbundet.se'], [78, 79, 76]], en: ['Personal care product allergy and sensitivity confusion', 'Consumers struggle to identify irritating ingredients in skincare, hair dye, fragrance, and cosmetics.', ['lakemedelsverket.se', 'astmaoallergiforbundet.se'], [78, 79, 76]] },
      { sv: ['Viktstöd är motsägelsefullt och stigmatiserande', 'Personer som vill få hälsosammare vanor möter motstridiga råd, skam, dyra program och begränsat individanpassat stöd.', ['Folkhälsomyndigheten', '1177.se'], [76, 78, 81]], en: ['Weight management advice is contradictory and stigmatizing', 'People seeking healthier habits face conflicting advice, shame, expensive programs, and limited personalized support.', ['Folkhälsomyndigheten', '1177.se'], [76, 78, 81]] },
      { sv: ['Äldre har svårt med läkemedelsrutiner', 'Äldre och anhöriga hanterar komplexa recept, utbyten, påfyllningstider och risk för missade eller dubbla doser.', ['lakemedelsverket.se', 'Socialstyrelsen'], [74, 77, 80]], en: ['Elderly people struggle with medication routines', 'Older patients and caregivers face complex prescriptions, substitutions, refill timing, and risk of missed or duplicate doses.', ['lakemedelsverket.se', 'Socialstyrelsen'], [74, 77, 80]] },
    ]
  },
  'travel-experiences': {
    sv: { name: 'Resor & upplevelser', subtitle: 'Svenska problem inom resor och upplevelser handlar om opålitliga transporter, återbetalningstvister, tillgänglighet, överturism och kostnadspress.' },
    en: { name: 'Travel & Experiences', subtitle: 'Swedish travel and experience problems center on unreliable transport, refund conflicts, accessibility, overtourism, and cost pressure.' },
    items: [
      { sv: ['Tågstrul gör inrikesresor opålitliga', 'Resenärer drabbas av förseningar, inställda avgångar, ersättningsbussar och bristande information vid tågstrul.', ['Trafikverket', 'sj.se'], [92, 86, 83]], en: ['Train disruptions make domestic travel unreliable', 'Travelers face delays, cancellations, replacement buses, and weak communication during rail disruptions.', ['Trafikverket', 'sj.se'], [92, 86, 83]] },
      { sv: ['Svårt att få ersättning vid flygförsening', 'Passagerare kämpar med flygbolagens formulär, avslag, långa svarstider och osäkerhet om EU-rättigheter.', ['ARN', 'Hallå Konsument'], [90, 86, 83]], en: ['Flight delay compensation is hard to claim', 'Passengers struggle with airline forms, rejected claims, long response times, and uncertainty about EU rights.', ['ARN', 'Hallå Konsument'], [90, 86, 83]] },
      { sv: ['Paketresors avbokningsvillkor förvirrar köpare', 'Konsumenter missförstår avbeställningsskydd, sjukdomsregler, force majeure och tider för återbetalning.', ['konsumentverket.se', 'ARN'], [88, 85, 83]], en: ['Package travel refunds and cancellation terms confuse buyers', 'Consumers misunderstand cancellation protection, illness rules, force majeure, and refund timelines.', ['konsumentverket.se', 'ARN'], [88, 85, 83]] },
      { sv: ['Biljettbedrägerier och andrahandsförsäljning skadar konsumenter', 'Köpare riskerar överprissatta, ogiltiga, kopierade eller uteblivna biljetter till konserter och sportevenemang.', ['Polisen', 'konsumentverket.se'], [86, 83, 82]], en: ['Event ticket resale and scams hurt consumers', 'Buyers risk overpriced, invalid, duplicated, or never-delivered tickets for concerts and sports events.', ['Polisen', 'konsumentverket.se'], [86, 83, 82]] },
      { sv: ['Tillgänglighetsinformation för resor är ofullständig', 'Resenärer med funktionsnedsättning har svårt att verifiera hissar, assistans, toaletter, hotellrum och aktiviteternas tillgänglighet.', ['mfd.se', 'Trafikverket'], [84, 82, 82]], en: ['Accessible travel information is incomplete', 'Travelers with disabilities struggle to verify step-free access, assistance, toilets, hotel rooms, and activity suitability.', ['mfd.se', 'Trafikverket'], [84, 82, 82]] },
      { sv: ['Landsbygds- och skärgårdsresor är svåra utan bil', 'Besökare och boende möter gles kollektivtrafik, säsongstidtabeller och svaga sista-kilometern-förbindelser.', ['Tillväxtverket', 'Trafikverket'], [82, 81, 87]], en: ['Rural and archipelago travel is difficult without a car', 'Visitors and residents face sparse public transport, seasonal timetables, and poor last-mile connections.', ['Tillväxtverket', 'Trafikverket'], [82, 81, 87]] },
      { sv: ['Dynamisk prissättning gör resebudget svår', 'Tåg-, flyg-, hotell- och aktivitetspriser ändras snabbt, vilket gör det svårt för familjer att planera prisvärda resor.', ['konsumentverket.se', 'SCB'], [80, 80, 86]], en: ['Dynamic pricing makes travel budgeting hard', 'Train, flight, hotel, and activity prices change quickly, making it difficult for families to plan affordable trips.', ['konsumentverket.se', 'SCB'], [80, 80, 86]] },
      { sv: ['Trängsel belastar populära natur- och stadsdestinationer', 'Populära platser får trängsel, skräp, parkeringspress, buller och boendefrustration under högsäsong.', ['Tillväxtverket', 'naturvardsverket.se'], [78, 79, 81]], en: ['Tourist crowding strains popular nature and city destinations', 'Popular areas see congestion, litter, parking pressure, noise, and resident frustration during peak seasons.', ['Tillväxtverket', 'naturvardsverket.se'], [78, 79, 81]] },
      { sv: ['Väderberoende upplevelser är riskabla att boka', 'Utomhusturer, skidåkning, båtliv och norrskensresor kan ställas in eller bli misslyckade på grund av väder.', ['smhi.se', 'Hallå Konsument'], [76, 78, 81]], en: ['Weather-dependent experiences are risky to book', 'Outdoor tours, skiing, boating, and northern lights trips can be cancelled or disappointing due to changing weather.', ['smhi.se', 'Hallå Konsument'], [76, 78, 81]] },
      { sv: ['Svårt att verifiera djur- och barnvänliga resor', 'Resenärer behöver pussla ihop regler för husdjur, barnvagnar, bilbarnstolar, familjerum och åldersgränser hos olika aktörer.', ['sj.se', 'Reddit'], [74, 78, 77]], en: ['Pet-friendly and family-friendly travel details are hard to verify', 'Travelers must piece together rules for pets, prams, child seats, family rooms, and age limits across providers.', ['sj.se', 'Reddit'], [74, 78, 77]] },
    ]
  },
  'outdoor-friluftsliv': {
    sv: { name: 'Friluftsliv & utomhusliv', subtitle: 'Svenska friluftslivsproblem rör tillgång, säkerhet, väder, utrustningskostnader, markkonflikter och miljöbelastning.' },
    en: { name: 'Outdoor & Friluftsliv', subtitle: 'Sweden’s outdoor life problems involve access, safety, weather, gear costs, land-use conflicts, and environmental pressure.' },
    items: [
      { sv: ['Nybörjare missförstår allemansrätten', 'Många är osäkra på var de får tälta, elda, plocka bär, cykla, ha hund eller passera privat mark.', ['naturvardsverket.se', 'lansstyrelsen.se'], [92, 86, 78]], en: ['Beginners misunderstand allemansrätten', 'People are unsure where they may camp, make fires, pick berries, bike, bring dogs, or cross private land.', ['naturvardsverket.se', 'lansstyrelsen.se'], [92, 86, 78]] },
      { sv: ['Svårt att följa lokala eldningsförbud', 'Vandrare och campare har svårt att veta aktuella eldningsregler mellan kommuner, län och skiftande väder.', ['MSB', 'lansstyrelsen.se'], [90, 85, 83]], en: ['Fire bans are hard to track locally', 'Hikers and campers struggle to know current fire rules across municipalities, counties, and changing weather conditions.', ['MSB', 'lansstyrelsen.se'], [90, 85, 83]] },
      { sv: ['Fästingar och fästingburna sjukdomar oroar friluftsutövare', 'Familjer och hundägare oroar sig för TBE, borrelia, fästingkontroll, vaccinationskostnad och regionala riskskillnader.', ['Folkhälsomyndigheten', '1177.se'], [88, 84, 83]], en: ['Ticks and tick-borne disease worry outdoor users', 'Families and dog owners worry about TBE, Lyme disease, tick checks, vaccination cost, and regional risk differences.', ['Folkhälsomyndigheten', '1177.se'], [88, 84, 83]] },
      { sv: ['Friluftsutrustning är dyr för sällananvändare', 'Många tvekar att prova vandring, skidåkning, paddling eller camping eftersom bra utrustning kräver stora inköp.', ['konsumentverket.se', 'Reddit'], [86, 84, 84]], en: ['Outdoor gear is expensive for occasional users', 'People hesitate to try hiking, skiing, paddling, or camping because quality gear costs a lot upfront.', ['konsumentverket.se', 'Reddit'], [86, 84, 84]] },
      { sv: ['Ledinformation är splittrad och inaktuell', 'Vandrare har svårt att hitta pålitlig information om ledstatus, vatten, vindskydd, transport, avstängningar och svårighetsgrad.', ['naturvardsverket.se', 'svenskaturistforeningen.se'], [84, 82, 77]], en: ['Trail information is fragmented and outdated', 'Hikers struggle to find reliable data on trail status, water sources, shelters, transport, closures, and difficulty.', ['naturvardsverket.se', 'svenskaturistforeningen.se'], [84, 82, 77]] },
      { sv: ['Trängsel vid leder skapar parkering och skräp', 'Populära naturområden saknar tillräcklig parkering, toaletter, sopkärl och skyltning under intensiva helger.', ['naturvardsverket.se', 'Tillväxtverket'], [82, 81, 82]], en: ['Crowded trailheads create parking and litter problems', 'Popular nature areas lack enough parking, toilets, bins, and signage during peak weekends.', ['naturvardsverket.se', 'Tillväxtverket'], [82, 81, 82]] },
      { sv: ['Hundregler i naturen är förvirrande', 'Hundägare har svårt med koppeltvång, häckningsperioder, renbetesområden, stränder, parker och naturreservat.', ['naturvardsverket.se', 'jordbruksverket.se'], [80, 80, 76]], en: ['Dog rules in nature are confusing', 'Dog owners struggle with leash rules, nesting-season restrictions, reindeer areas, beaches, parks, and nature reserves.', ['naturvardsverket.se', 'jordbruksverket.se'], [80, 80, 76]] },
      { sv: ['Svag mobiltäckning och krisberedskap i avlägsna områden', 'Friluftsutövare kan tappa täckning och underskatta navigering, väder, batteri och räddningsrisker i fjäll och skog.', ['PTS', 'fjallsakerhetsradet.se'], [78, 79, 81]], en: ['Mobile coverage and emergency readiness are weak in remote areas', 'Outdoor users can lose signal and underestimate navigation, weather, battery, and rescue risks in mountains and forests.', ['PTS', 'fjallsakerhetsradet.se'], [78, 79, 81]] },
      { sv: ['Vattensäkerhetsrisker kvarstår i sjöar, kust och vinteris', 'Badare, paddlare, fiskare och skridskoåkare riskerar drunkning, köldchock, svag is och bristande säkerhetsrutiner.', ['MSB', 'issakerhet.se'], [76, 78, 81]], en: ['Water safety risks persist in lakes, coasts, and winter ice', 'Swimmers, paddlers, anglers, and skaters face drowning risk, cold shock, weak ice, and poor safety habits.', ['MSB', 'issakerhet.se'], [76, 78, 81]] },
      { sv: ['Konflikter ökar mellan friluftsliv och känslig natur', 'Ökat friluftsliv kan störa djurliv, skada vegetation, slita leder och skapa konflikter med markägare eller renskötsel.', ['naturvardsverket.se', 'sametinget.se'], [74, 77, 75]], en: ['Conflicts grow between recreation and sensitive nature', 'Increased outdoor use can disturb wildlife, damage vegetation, erode trails, and clash with landowners or reindeer herding.', ['naturvardsverket.se', 'sametinget.se'], [74, 77, 75]] },
    ]
  }
} as const;

export const categoryOrder = ['public-sector-welfare', 'housing-real-estate', 'healthtech', 'elder-care', 'greentech-sustainability', 'integration-immigration', 'consumer-services', 'home-services', 'fintech-payments', 'logistics-delivery-infrastructure', 'mobility-micromobility', 'b2b-services', 'saas', 'edtech', 'food-beverage', 'ecommerce', 'cold-climate-seasonal', 'health-wellness-personal-care', 'travel-experiences', 'outdoor-friluftsliv'] as const;

export type Language = keyof typeof ui;
export type CategoryId = keyof typeof categories;
