export const ui = {
      sv: {
        brandName: 'Fix My Itch Sverige',
        brandSub: 'Top 10 svenska problem per kategori',
        navTop10: 'Top 10', navInsight: 'Insikt', navMethod: 'Metod', navArchitecture: 'Arkitektur', navArchBtn: 'Se arkitektur', navCta: 'Utforska problem',
        heroEyebrow: 'Sverige-first founder intelligence',
        heroTitle: 'Start where Sweden itches.',
        heroLead: 'Ett kuraterat, Sverige-först urval av de 10 viktigaste problemen inom varje kategori — byggt för grundare som vill börja med verklig friktion, inte slumpmässiga idéer.',
        heroPrimary: 'Se Top 10', heroSecondary: 'Hur vi väljer', proof1: 'problem per kategori', proof2: 'kuraterade startkategorier', proof3: 'senast uppdaterad',
        previewHeader: 'Veckans starkaste kategori', previewStatus: 'Hög signal', previewTitle: 'Småföretag & administration', previewBody: 'När svenska småföretag fastnar i fakturaflöden, redovisning, myndighetskontakt och manuella backoffice-steg skapas ett tydligt byggfönster.', previewNote: 'Inga oändliga listor. Bara de 10 starkaste problemen per kategori, med tydlig rangordning och founder-läsbar motivering.',
        metric1: 'Topprankad klåda', metric2: 'Betalvilja', metric3: 'Adoption',
        topTitle: 'Top 10 problem per kategori', topLead: 'Välj en kategori och se exakt 10 problem. Inte en gigantisk databas. Inte allt på en gång. Bara det mest byggvärda urvalet.',
        insightLabel: 'Veckans insikt', insightTitle: 'Det bästa founder-materialet är nästan alltid kuraterat hårdare än det är insamlat.', insightBody1: 'Den publika upplevelsen ska kännas självklar: välj kategori, få de 10 viktigaste problemen, förstå varför de betyder något. Allt annat — större datamängder, klustring, scoring och källarbete — kan leva bakom kulisserna.', insightBody2: 'Det gör sajten renare, mer premium och mer trovärdig. Besökaren ska känna att någon redan gjort det svåra prioriteringsarbetet.', insightCta: 'Se metodiken',
        methodLabel: 'Metod', methodTitle: 'Varför bara 10?', methodBody: 'För att knapphet signalerar omdöme. Varje kategori publicerar endast de 10 mest lovande problemen enligt severity, frekvens, whitespace, svensk relevans, tillit och sannolik adoption.',
        missionLabel: 'Vårt uppdrag', missionTitle: 'This is our gift to the next gen of founders to satisfy their itch and build what’s next.', missionBody: 'Vi vill göra det lättare att börja på rätt plats: där svenska människor, hushåll, företag och institutioner faktiskt känner friktion. Inte med en lista över allt — utan med ett koncentrerat urval av det som verkligen förtjänar att byggas kring.',
        missionMini1: 'Sverige först', missionMini1Body: 'Lokalt språk, svenska system och kontext som faktiskt betyder något här.', missionMini2: 'Kuraterat över komplett', missionMini2Body: 'Den publika produkten visar bara de 10 viktigaste problemen per kategori.', missionMini3: 'Founder utility', missionMini3Body: 'Varje rad ska hjälpa någon prioritera vad som är värt att bygga.',
        footerLeft: 'Fix My Itch Sverige — ombyggd som en kuraterad Top 10-upplevelse per kategori.', footerRight: 'Se arkitekturdiagrammet',
        countLabel: '10 problem · kuraterat urval', rank: 'Rank', itch: 'Klåda', market: 'Marknad', trust: 'Tillit',
        methodScores: [
          ['Severity', 'Hur dyrt, frustrerande eller riskfyllt problemet är.'],
          ['Frequency', 'Hur ofta det återkommer i svensk vardag eller drift.'],
          ['Whitespace', 'Hur dåligt dagens lösningar täcker behovet.'],
          ['Lagom adoption', 'Hur realistiskt det är att folk faktiskt byter beteende.']
        ]
      },
      en: {
        brandName: 'Fix My Itch Sweden',
        brandSub: 'Top 10 real problems in Sweden by category',
        navTop10: 'Top 10', navInsight: 'Insight', navMethod: 'Method', navArchitecture: 'Architecture', navArchBtn: 'See architecture', navCta: 'Explore problems',
        heroEyebrow: 'Sweden-first founder intelligence',
        heroTitle: 'Start where Sweden itches.',
        heroLead: 'A curated, Sweden-first selection of the 10 most important problems in each category — built for founders who want to start from real friction, not random ideas.',
        heroPrimary: 'See the Top 10', heroSecondary: 'How we choose', proof1: 'problems per category', proof2: 'curated launch categories', proof3: 'last updated',
        previewHeader: 'Strongest category this week', previewStatus: 'High signal', previewTitle: 'Small business admin overload', previewBody: 'When Swedish small businesses get stuck in invoicing, bookkeeping, agency contact and manual back-office steps, a clear build window appears.', previewNote: 'No endless lists. Just the strongest 10 problems in each category, ranked clearly and explained in founder-readable language.',
        metric1: 'Top itch score', metric2: 'Willingness to pay', metric3: 'Adoption',
        topTitle: 'Top 10 problems by category', topLead: 'Choose a category and see exactly 10 problems. Not a giant database. Not everything at once. Just the most build-worthy selection.',
        insightLabel: 'Insight of the week', insightTitle: 'The best founder material is almost always curated harder than it is collected.', insightBody1: 'The public experience should feel obvious: choose a category, get the 10 most important problems, understand why they matter. Everything else — larger datasets, clustering, scoring and source work — can stay behind the curtain.', insightBody2: 'That makes the product cleaner, more premium and more credible. Visitors should feel that someone already did the hard prioritisation work.', insightCta: 'See the method',
        methodLabel: 'Method', methodTitle: 'Why only 10?', methodBody: 'Because scarcity signals judgment. Each category publishes only the 10 most promising problems based on severity, recurrence, whitespace, Swedish relevance, trust and likely adoption.',
        missionLabel: 'Our mission', missionTitle: 'This is our gift to the next gen of founders to satisfy their itch and build what’s next.', missionBody: 'We want to make it easier to start in the right place: where people, households, companies and institutions in Sweden actually feel friction. Not with a list of everything — but with a concentrated selection of what truly deserves to be built around.',
        missionMini1: 'Sweden first', missionMini1Body: 'Local language, Swedish systems and context that actually matters here.', missionMini2: 'Curated over complete', missionMini2Body: 'The public product shows only the 10 most important problems in each category.', missionMini3: 'Founder utility', missionMini3Body: 'Every row should help someone decide what is worth building.',
        footerLeft: 'Fix My Itch Sweden — rebuilt as a curated Top 10 per category experience.', footerRight: 'See the architecture diagram',
        countLabel: '10 problems · curated selection', rank: 'Rank', itch: 'Itch', market: 'Market', trust: 'Trust',
        methodScores: [
          ['Severity', 'How expensive, painful or risky the problem feels.'],
          ['Frequency', 'How often it recurs in Swedish life or operations.'],
          ['Whitespace', 'How poorly current solutions cover the need.'],
          ['Lagom adoption', 'How realistic it is that people would actually change behaviour.']
        ]
      }
    } as const;

export const categories = {
      smb: {
        sv: { name: 'Småföretag & administration', subtitle: 'För founders som vill bygga för SME-drift, backoffice och finansiell vardagsfriktion.' },
        en: { name: 'Small business & admin', subtitle: 'For founders building around SME operations, back office friction and financial workflows.' },
        items: [
          { sv: ['Fakturor som kräver för mycket handpåläggning', 'Svenska småbolag sitter fortfarande med splittrade flöden för faktura, påminnelse och avstämning.', ['FinTech','B2B'], [84,79,66]], en: ['Invoicing that still needs too much manual work', 'Swedish small firms still operate fragmented flows for invoicing, reminders and reconciliation.', ['FinTech','B2B'], [84,79,66]] },
          { sv: ['Moms, kvitton och bokföring i tre olika system', 'Ekonomiarbetet blir onödigt tungt när underlag och rapportering lever i olika verktyg.', ['Accounting','SaaS'], [82,77,70]], en: ['VAT, receipts and bookkeeping across three systems', 'Finance work gets unnecessarily heavy when documentation and reporting live in separate tools.', ['Accounting','SaaS'], [82,77,70]] },
          { sv: ['Löneflöden som inte passar små team', 'Mikroteam behöver enklare löne- och personalflöden än dagens standardverktyg ofta erbjuder.', ['HR','SME'], [79,73,71]], en: ['Payroll flows that do not fit tiny teams', 'Micro teams need simpler payroll and people workflows than standard tools usually provide.', ['HR','SME'], [79,73,71]] },
          { sv: ['Myndighetskontakt utan sammanhållen överblick', 'Företagare jagar status och dokument över flera digitala gränssnitt utan tydlig sammanfattning.', ['GovTech','Workflow'], [78,72,75]], en: ['Agency coordination without a single view', 'Business owners chase status and documents across separate government interfaces without one clear summary.', ['GovTech','Workflow'], [78,72,75]] },
          { sv: ['Kassaflödesoro trots lönsam försäljning', 'Många småbolag har intäkter men saknar verktyg för kortsiktig kassaflödeskontroll.', ['Finance','SME'], [78,80,64]], en: ['Cash-flow anxiety despite healthy sales', 'Many small firms generate revenue but still lack tools for short-term cash visibility.', ['Finance','SME'], [78,80,64]] },
          { sv: ['Upphandlingar och anbud känns för tunga för små aktörer', 'Mindre bolag ser möjligheter men orkar inte processfriktionen i offentliga eller större affärer.', ['Public Sector','B2B'], [74,70,72]], en: ['Tenders feel too heavy for smaller operators', 'Small firms see opportunity but cannot absorb the process friction of public or larger deals.', ['Public Sector','B2B'], [74,70,72]] },
          { sv: ['Rapportering för hållbarhet som blir administrativ börda', 'Krav på hållbarhetsdata ökar snabbare än SME-verktygen hänger med.', ['GreenTech','Compliance'], [72,75,67]], en: ['Sustainability reporting that turns into admin burden', 'Pressure for sustainability data is rising faster than SME tooling can keep up.', ['GreenTech','Compliance'], [72,75,67]] },
          { sv: ['Försäljningsdata utan beslutsstöd', 'Små företag har data men inte tydlig vägledning för vilka kunder, produkter eller kanaler som driver mest.', ['Analytics','SME'], [71,74,63]], en: ['Sales data without decision support', 'Small businesses have data but lack clear guidance on which customers, products or channels matter most.', ['Analytics','SME'], [71,74,63]] },
          { sv: ['Kundsupport skött i inkorgar och DM:s', 'Supportflöden växer fram organiskt och blir svåra att mäta eller standardisera.', ['Support','SaaS'], [69,68,61]], en: ['Customer support handled in inboxes and DMs', 'Support grows organically and becomes hard to measure or standardise.', ['Support','SaaS'], [69,68,61]] },
          { sv: ['SME-ägare saknar enkel helhetsbild varje morgon', 'Dagens viktigaste ekonomi-, drift- och personalstatus är ofta utspridd i flera appar.', ['Dashboard','Workflow'], [68,69,70]], en: ['Owners lack a simple morning overview', 'The day’s most important finance, operations and team status is often spread across multiple apps.', ['Dashboard','Workflow'], [68,69,70]] }
        ]
      },
      housing: {
        sv: { name: 'Boende & bostadsrätt', subtitle: 'För problem kring BRF-liv, hemunderhåll, boendekostnad och beslut i vardagen.' },
        en: { name: 'Housing & BRF', subtitle: 'For problems around housing associations, home upkeep, housing costs and everyday decisions.' },
        items: [
          { sv: ['BRF-beslut utan bra underlag', 'Styrelser behöver bättre jämförelser, konsekvensbilder och kommunikation innan beslut tas.', ['BRF','Decision'], [81,73,77]], en: ['BRF decisions without strong decision support', 'Association boards need better comparisons, consequence views and communication before decisions are made.', ['BRF','Decision'], [81,73,77]] },
          { sv: ['Underhållsplaner som lever i PDF:er och huvuden', 'Planering av fastighetsunderhåll tappar fart när kunskap inte är levande eller sökbar.', ['Property','Planning'], [79,71,75]], en: ['Maintenance plans trapped in PDFs and people’s heads', 'Property upkeep slows down when knowledge is not live, structured or searchable.', ['Property','Planning'], [79,71,75]] },
          { sv: ['Boende förstår inte vad avgiftshöjningar egentligen betyder', 'Många hushåll ser höjningen men inte drivarna eller alternativen.', ['Housing','Finance'], [77,76,69]], en: ['Residents do not understand what fee increases really mean', 'Many households see the increase but not the drivers behind it or the alternatives.', ['Housing','Finance'], [77,76,69]] },
          { sv: ['Renoveringsval görs utan tydlig kostnadsbild', 'Privatpersoner jämför offerter, risker och standarder i onödigt manuella processer.', ['Consumer','Home Services'], [76,78,66]], en: ['Renovation choices happen without a clear cost picture', 'Consumers compare quotes, risks and standards through overly manual processes.', ['Consumer','Home Services'], [76,78,66]] },
          { sv: ['Skador i hemmet leder till förvirring mellan försäkring och åtgärd', 'När något går sönder blir ansvarsfrågan och nästa steg ofta otydliga.', ['Insurance','Home'], [75,72,74]], en: ['Home damage creates confusion between insurance and action', 'When something breaks, ownership and next steps are often unclear.', ['Insurance','Home'], [75,72,74]] },
          { sv: ['Energibeslut i bostäder tas utan enkel simulering', 'Många hushåll och föreningar vill effektivisera men saknar lättförståeliga beslutsverktyg.', ['Energy','GreenTech'], [74,74,72]], en: ['Home energy decisions happen without simple simulation', 'Households and associations want to improve efficiency but lack easy decision tools.', ['Energy','GreenTech'], [74,74,72]] },
          { sv: ['Andrahandsuthyrning är administrativt segt', 'Regler, godkännanden och dokumentation skapar onödigt mycket handpåläggning.', ['Rental','Workflow'], [71,67,70]], en: ['Subletting is administratively slow', 'Rules, approvals and documentation create too much manual handling.', ['Rental','Workflow'], [71,67,70]] },
          { sv: ['Boende saknar tydlig kanal för små vardagsproblem', 'Mindre ärenden om ljud, gemensamma ytor och drift blir ofta felprioriterade.', ['Community','Ops'], [69,70,65]], en: ['Residents lack a clear channel for small daily issues', 'Minor issues around noise, shared spaces and operations are often poorly prioritised.', ['Community','Ops'], [69,70,65]] },
          { sv: ['Flytt och inflyttning är onödigt splittrade upplevelser', 'Adresser, abonnemang, nycklar och lokalinformation hänger inte ihop.', ['Moving','Consumer'], [68,72,63]], en: ['Moving and move-in are unnecessarily fragmented experiences', 'Addresses, subscriptions, keys and local information do not connect cleanly.', ['Moving','Consumer'], [68,72,63]] },
          { sv: ['Hemservice marknaden känns opålitlig att navigera', 'Många hushåll vet inte vem de ska lita på för små och återkommande jobb.', ['Marketplace','Trust'], [67,71,76]], en: ['The home services market feels unreliable to navigate', 'Many households are unsure who to trust for small and recurring jobs.', ['Marketplace','Trust'], [67,71,76]] }
        ]
      },
      welfare: {
        sv: { name: 'Välfärd & äldreomsorg', subtitle: 'För problem där vård, kommun, familj och tillit möts.' },
        en: { name: 'Welfare & elder care', subtitle: 'For problems where care, municipalities, family and trust intersect.' },
        items: [
          { sv: ['Anhöriga blir operativ projektledare åt vården', 'Familjemedlemmar samordnar möten, mediciner, beslut och transport utan ett gemensamt system.', ['Healthtech','Care'], [83,74,89]], en: ['Families become the operational layer of care', 'Relatives coordinate visits, medication, decisions and transport without a shared system.', ['Healthtech','Care'], [83,74,89]] },
          { sv: ['Kommunikation mellan hemtjänst och familj är ojämn', 'Information kommer sent, i fel kanal eller utan tydlig kontext.', ['GovTech','Care'], [81,71,86]], en: ['Communication between home care and families is uneven', 'Information arrives late, in the wrong channel or without clear context.', ['GovTech','Care'], [81,71,86]] },
          { sv: ['Digitala vårdflöden fungerar sämre för äldre med låg digital vana', 'Systemen finns, men användbarheten är inte byggd för hela målgruppen.', ['Accessibility','Health'], [80,76,88]], en: ['Digital care flows break down for older users with low digital comfort', 'The systems exist, but usability is not built for the full audience.', ['Accessibility','Health'], [80,76,88]] },
          { sv: ['Läkemedelsöverblick saknar familjeläge', 'Anhöriga behöver bättre förståelse för vad som ändrats, när och varför.', ['Medication','Family'], [79,69,85]], en: ['Medication management lacks a family mode', 'Relatives need a better view of what changed, when and why.', ['Medication','Family'], [79,69,85]] },
          { sv: ['Korttidsboende och tillfälliga insatser är svåra att navigera', 'Behovet uppstår snabbt men besluts- och planeringsstödet är tunt.', ['Care Ops','Planning'], [77,68,82]], en: ['Short-term care and temporary support are hard to navigate', 'The need appears quickly but planning and decision support is thin.', ['Care Ops','Planning'], [77,68,82]] },
          { sv: ['Äldre med flera vårdaktörer får ingen sammanhållen vardagsvy', 'Olika delar fungerar var för sig men inte tillsammans för hushållet.', ['Coordination','Health'], [76,70,84]], en: ['Older adults with multiple care providers lack one everyday view', 'Different pieces work individually, but not together for the household.', ['Coordination','Health'], [76,70,84]] },
          { sv: ['Trygghetsfrågor i hemmet fångas för sent', 'Små signaler om ensamhet, fallrisk eller rutinförändringar är svåra att följa upp utan att bli invasiv.', ['Safety','Home'], [75,65,90]], en: ['Home safety issues get caught too late', 'Small signals around loneliness, fall risk or routine change are hard to monitor without becoming invasive.', ['Safety','Home'], [75,65,90]] },
          { sv: ['Stöd till anhöriga är svårt att hitta vid rätt tidpunkt', 'Information finns, men upptäcks ofta först när belastningen redan är hög.', ['Support','Public Sector'], [72,67,79]], en: ['Support for caregivers is hard to find at the right moment', 'Information exists, but is often discovered only after the burden is already high.', ['Support','Public Sector'], [72,67,79]] },
          { sv: ['Övergångar mellan sjukhus, hem och kommun skapar informationsglapp', 'Just när risknivån är högst blir informationen mest fragmenterad.', ['Discharge','Coordination'], [71,66,83]], en: ['Transitions between hospital, home and municipality create information gaps', 'Exactly when risk is highest, information becomes most fragmented.', ['Discharge','Coordination'], [71,66,83]] },
          { sv: ['Framtidsplanering kring vård och vardag börjar för sent', 'Samtal om behov, ekonomi och ansvar sker ofta först när situationen blivit akut.', ['Planning','Family'], [69,64,81]], en: ['Future planning for care and daily life starts too late', 'Conversations about needs, finances and responsibility often begin only when the situation is urgent.', ['Planning','Family'], [69,64,81]] }
        ]
      },
      integration: {
        sv: { name: 'Integration & vardagssystem', subtitle: 'För problem där språk, myndigheter, arbete och digital förståelse krockar.' },
        en: { name: 'Integration & everyday systems', subtitle: 'For problems where language, institutions, work and digital understanding collide.' },
        items: [
          { sv: ['Ny i Sverige men inget ställe för hela systemförståelsen', 'Många förstår enskilda steg men inte hur BankID, personnummer, vård, skola och arbete hänger ihop.', ['Integration','Public Sector'], [80,75,85]], en: ['New to Sweden with no single place for system understanding', 'Many people understand individual steps but not how BankID, identity, healthcare, school and work fit together.', ['Integration','Public Sector'], [80,75,85]] },
          { sv: ['Myndighetsspråk är digitalt tillgängligt men inte begripligt', 'Formellt korrekt språk räcker inte när beslut måste omsättas i handling.', ['Language','GovTech'], [79,78,82]], en: ['Agency language is digitally available but still hard to understand', 'Formal correctness is not enough when decisions must turn into action.', ['Language','GovTech'], [79,78,82]] },
          { sv: ['Vägen till första jobbet är splittrad mellan flera aktörer', 'Arbetsförmedling, kommun, nätverk och utbildning bildar ingen tydlig resa.', ['Jobs','Mobility'], [78,74,77]], en: ['The path to a first job is fragmented across multiple actors', 'Employment services, municipalities, networks and training do not form one clear journey.', ['Jobs','Mobility'], [78,74,77]] },
          { sv: ['Praktisk vardagsinformation är svår att lokalisera vid rätt tid', 'Hyresregler, försäkring, vårdval och skola hittas ofta genom ad hoc-forum i stället för strukturerade flöden.', ['Consumer','Guidance'], [77,73,74]], en: ['Practical daily-life information is hard to find at the right moment', 'Housing, insurance, healthcare choice and school information is often found through ad hoc forums instead of structured guidance.', ['Consumer','Guidance'], [77,73,74]] },
          { sv: ['Utbildad kompetens översätts dåligt till svensk arbetsmarknad', 'Många kan mycket men saknar rätt bro mellan erfarenhet och svensk efterfrågan.', ['Upskilling','Work'], [76,72,75]], en: ['Skilled experience translates poorly into the Swedish job market', 'Many people have real capability but lack the bridge to Swedish demand.', ['Upskilling','Work'], [76,72,75]] },
          { sv: ['Familjer får bygga egna checklistor för skolstart och barnsystem', 'Det saknas sammanhållen onboarding för hur familjelivet faktiskt fungerar lokalt.', ['Family','Education'], [74,68,73]], en: ['Families build their own checklists for school start and child systems', 'There is no coherent onboarding for how family life actually works locally.', ['Family','Education'], [74,68,73]] },
          { sv: ['Nyanlända småföretagare saknar smidig väg in i svenska SME-flöden', 'Bolagsstart, skatt, fakturering och compliance känns onödigt fragmenterat.', ['SME','Integration'], [73,71,76]], en: ['Newcomer founders lack a smooth entry into Swedish SME systems', 'Company setup, tax, invoicing and compliance feel unnecessarily fragmented.', ['SME','Integration'], [73,71,76]] },
          { sv: ['Tillitskrävande tjänster saknar inkluderande första steg', 'Produkter som kräver identitet, betalning eller dokumentation förlorar användare tidigt.', ['Onboarding','Trust'], [71,67,79]], en: ['Trust-heavy services lack inclusive first steps', 'Products requiring identity, payment or documentation lose users early.', ['Onboarding','Trust'], [71,67,79]] },
          { sv: ['Lokalt stöd och föreningsliv är svårt att upptäcka digitalt', 'Människor lär sig ofta sent vilka gemenskaper eller resurser som finns nära dem.', ['Community','Discovery'], [69,65,72]], en: ['Local support and community groups are hard to discover digitally', 'People often learn too late which resources or communities exist near them.', ['Community','Discovery'], [69,65,72]] },
          { sv: ['Många beslut känns binära trots att människor behöver nästa lilla steg', 'Det finns ett gap mellan full rådgivning och enkel, praktisk vägledning.', ['Guidance','UX'], [67,66,70]], en: ['Too many decisions feel binary when people need the next small step', 'There is a gap between full advisory services and simple practical guidance.', ['Guidance','UX'], [67,66,70]] }
        ]
      },
      climate: {
        sv: { name: 'Klimat, energi & vintervardag', subtitle: 'För problem där Sverige blir som tydligast: kyla, energi, säsong och vardagsresiliens.' },
        en: { name: 'Climate, energy & winter life', subtitle: 'For distinctly Swedish problems shaped by cold, energy, seasonality and resilience.' },
        items: [
          { sv: ['Hushåll vet att de borde energieffektivisera men inte vad som lönar sig först', 'Många beslut stoppas av jämförelsefriktion och osäker payoff.', ['Energy','Consumer'], [79,77,73]], en: ['Households know they should improve energy efficiency but not what pays off first', 'Many decisions stall on comparison friction and uncertain returns.', ['Energy','Consumer'], [79,77,73]] },
          { sv: ['Vinterunderhåll i hemmet är reaktivt i stället för planerat', 'Små problem växer när ingen samlar risker, checkpunkter och timing.', ['Winter','Home'], [77,74,70]], en: ['Winter home maintenance is reactive instead of planned', 'Small issues grow when no one brings together risks, checkpoints and timing.', ['Winter','Home'], [77,74,70]] },
          { sv: ['Villaägare saknar enkel bild av energidata i vardagsspråk', 'Data finns men översätts dåligt till beslut som känns genomförbara.', ['Data','Energy'], [76,72,68]], en: ['Homeowners lack an everyday-language view of energy data', 'The data exists but is poorly translated into practical decisions.', ['Data','Energy'], [76,72,68]] },
          { sv: ['Elprisoro skapar ständig mikrostress utan tydlig handling', 'Många följer priset men saknar verktyg för vad de faktiskt ska ändra.', ['Electricity','Behaviour'], [75,78,65]], en: ['Electricity price anxiety creates constant micro-stress without action', 'Many people track prices but lack tools for what they should actually change.', ['Electricity','Behaviour'], [75,78,65]] },
          { sv: ['Snö, halka och vardagslogistik hanteras fortfarande för manuellt', 'Allt från uppfarter till leveranser och skolresor påverkas när vädret slår om.', ['Mobility','Winter'], [74,71,71]], en: ['Snow, ice and daily logistics are still managed too manually', 'Everything from driveways to deliveries and school runs is affected when weather shifts.', ['Mobility','Winter'], [74,71,71]] },
          { sv: ['Små föreningar och fastigheter har svårt att välja rätt gröna investeringar', 'Det finns många alternativ men svagt beslutsstöd för prioritering.', ['GreenTech','Property'], [73,70,69]], en: ['Small associations and buildings struggle to pick the right green investments', 'There are many options but weak prioritisation support.', ['GreenTech','Property'], [73,70,69]] },
          { sv: ['Reservkraft och beredskap i hemmet känns abstrakt tills något händer', 'Beredskapsinformation är ofta informativ men inte omsatt i hushållsplanering.', ['Resilience','Safety'], [72,67,78]], en: ['Backup power and home preparedness feel abstract until something happens', 'Preparedness guidance is informative but not translated into household planning.', ['Resilience','Safety'], [72,67,78]] },
          { sv: ['Vinterturism och friluftsliv har små men återkommande planeringsglapp', 'Resor, utrustning, väder och säkerhet kräver bättre samordning.', ['Travel','Outdoor'], [70,64,66]], en: ['Winter travel and outdoor life have recurring planning gaps', 'Trips, gear, weather and safety need better coordination.', ['Travel','Outdoor'], [70,64,66]] },
          { sv: ['Vardagspendling påverkas hårt av säsong utan bra alternativmotorik', 'När vinterförutsättningar ändras saknas ofta plan B i realtid.', ['Commuting','Mobility'], [69,69,67]], en: ['Daily commuting is heavily shaped by seasonality without good fallback logic', 'When winter conditions change, people often lack a real-time plan B.', ['Commuting','Mobility'], [69,69,67]] },
          { sv: ['Många hållbarhetsverktyg känns för avancerade för vanliga hushåll', 'Gränsen mellan insikt och handlingsförmåga är fortfarande för bred.', ['UX','Sustainability'], [67,68,64]], en: ['Many sustainability tools still feel too advanced for everyday households', 'The gap between insight and action remains too wide.', ['UX','Sustainability'], [67,68,64]] }
        ]
      },
      public: {
        sv: { name: 'Offentlig sektor & vardagsmyndigheter', subtitle: 'För problem där svenska invånare och företag möter offentliga flöden som borde vara enklare.' },
        en: { name: 'Public sector & everyday government', subtitle: 'For problems where residents and companies meet public flows that should be simpler.' },
        items: [
          { sv: ['Invånaren måste själv förstå hur flera myndigheter hänger ihop', 'Många tjänster är digitala men den övergripande resan är fortfarande användarens problem.', ['GovTech','Citizen'], [80,76,83]], en: ['People must personally figure out how multiple agencies fit together', 'Many services are digital, but the overall journey is still the user’s problem.', ['GovTech','Citizen'], [80,76,83]] },
          { sv: ['Status på ärenden är ofta synlig men inte meningsfull', 'Man ser att något pågår men inte vad nästa steg är eller hur lång tid det rimligen tar.', ['Workflow','GovTech'], [78,73,80]], en: ['Case status is often visible but not meaningful', 'You can see that something is happening, but not what comes next or how long it should take.', ['Workflow','GovTech'], [78,73,80]] },
          { sv: ['Återkommande blankettlogik skapar onödig kognitiv last', 'Samma typ av information matas in gång på gång i olika format.', ['Forms','UX'], [77,75,77]], en: ['Repeated form logic creates unnecessary cognitive load', 'The same information gets re-entered again and again in different formats.', ['Forms','UX'], [77,75,77]] },
          { sv: ['Digital self-service fungerar dåligt när ärendet blir ovanligt', 'Så fort användaren lämnar standardfallet blir stödet sämre och osäkerheten högre.', ['Self-service','Support'], [76,72,79]], en: ['Digital self-service breaks down once the case becomes atypical', 'The moment users leave the standard case, support weakens and uncertainty rises.', ['Self-service','Support'], [76,72,79]] },
          { sv: ['Kommunal information är lokal men sällan personlig', 'Invånare får mycket information men inte alltid den som är mest relevant för deras läge.', ['Municipal','Personalisation'], [74,69,74]], en: ['Municipal information is local but rarely personal', 'Residents get lots of information, but not always the information most relevant to their situation.', ['Municipal','Personalisation'], [74,69,74]] },
          { sv: ['Små företag har svårt att se hela offentliga kostnadsbilden', 'Avgifter, regler och rapporteringskrav kommer från flera håll utan samlad vy.', ['SME','GovTech'], [73,71,75]], en: ['Small firms struggle to see the full public-cost picture', 'Fees, rules and reporting obligations come from many directions without one view.', ['SME','GovTech'], [73,71,75]] },
          { sv: ['Människor förstår ofta beslut för sent', 'Brev, besked och digital information landar men förklarar inte alltid konsekvensen i praktiken.', ['Communication','Policy'], [72,70,78]], en: ['People often understand decisions too late', 'Letters and digital notices arrive, but do not always explain the practical consequence.', ['Communication','Policy'], [72,70,78]] },
          { sv: ['Bokning, ombokning och kölogik är ofta mer stressande än nödvändigt', 'När tider är knappa blir användarupplevelsen avgörande och ofta undermålig.', ['Scheduling','UX'], [70,68,72]], en: ['Booking, rescheduling and queue logic are more stressful than necessary', 'When slots are limited, the experience matters deeply and is often weak.', ['Scheduling','UX'], [70,68,72]] },
          { sv: ['Tillgänglighet för språk och stödbehov kommer in för sent i flödet', 'Anpassningen borde börja tidigare, inte efter att användaren redan fastnat.', ['Accessibility','Inclusion'], [69,66,81]], en: ['Accessibility for language and support needs arrives too late in the flow', 'Adaptation should begin earlier, not after the user is already stuck.', ['Accessibility','Inclusion'], [69,66,81]] },
          { sv: ['Många offentliga tjänster saknar lugn uppföljning efter avslutat ärende', 'Användaren lämnas ofta utan nästa steg, trygghet eller förståelse för vad som händer sedan.', ['Aftercare','Trust'], [67,64,76]], en: ['Many public services lack calm follow-up after the case closes', 'Users are often left without next steps, reassurance or understanding of what happens afterwards.', ['Aftercare','Trust'], [67,64,76]] }
        ]
      }
    } as const;

export const categoryOrder = ['smb', 'housing', 'welfare', 'integration', 'climate', 'public'] as const;

export type Language = keyof typeof ui;
export type CategoryId = keyof typeof categories;
